// RAID QIX v1.2.1
(function ensureV121LoadoutDom(){
  const cg=document.getElementById('charmGrid');
  if(cg&&!cg.classList.contains('equipStrip')){
    cg.className='equipStrip';
    cg.innerHTML=`<button class="equipSlot" data-equip-slot="0"><span class="equipIndex">01</span><strong>EMPTY</strong><small>DROP / CLICK TO REMOVE</small></button><button class="equipSlot" data-equip-slot="1"><span class="equipIndex">02</span><strong>EMPTY</strong><small>DROP / CLICK TO REMOVE</small></button>`;
  }
  const oldGrid=document.getElementById('inventoryGrid');
  if(oldGrid&&!oldGrid.classList.contains('mcInventoryGrid')){
    const sec=oldGrid.closest('.section');
    if(sec){
      sec.classList.add('inventorySection');
      sec.innerHTML=`<h3>INVENTORY</h3><div class="inventoryWorkbench"><div class="inventoryPane"><div id="inventoryGrid" class="mcInventoryGrid"></div><div class="section muted" id="inventoryText"></div></div><div id="itemDetail" class="inventoryDetail"><strong>SELECT AN ITEM</strong><small>クリックで詳細。ドラッグで装備/合成。</small></div></div>`;
    }
  }
})();
const INVENTORY_VISIBLE_MIN=54;
function equippedSlotOf(uid){return state.equippedCharms.findIndex(x=>x===uid)}
function saveEquipped(){state.equippedCharms=state.equippedCharms.filter(uid=>proceduralCharmByUid(uid)).slice(0,2);save('raidqix.charms',state.equippedCharms);updateHud()}
function equipCharmToSlot(uid,slot){const charm=proceduralCharmByUid(uid);if(!charm||slot<0||slot>1)return false;state.equippedCharms=state.equippedCharms.filter(x=>x!==uid);while(state.equippedCharms.length<2)state.equippedCharms.push(null);state.equippedCharms[slot]=uid;state.equippedCharms=state.equippedCharms.filter(Boolean);saveEquipped();renderLoadoutV121();v121RenderDetail(charm);return true}
function unequipSlot(slot){if(slot<0||slot>1)return;const next=[state.equippedCharms[0]||null,state.equippedCharms[1]||null];next[slot]=null;state.equippedCharms=next.filter(Boolean);saveEquipped();renderLoadoutV121();v121RenderDetail(proceduralCharmByUid(state.selectedInventoryCharm)||null)}
function unequipCharmUid(uid){state.equippedCharms=state.equippedCharms.filter(x=>x!==uid);saveEquipped();renderLoadoutV121();v121RenderDetail(proceduralCharmByUid(state.selectedInventoryCharm)||null)}
function charmGlyph(c){if(!c?.affixes?.length)return '◇';const k=c.affixes[0].key;return ({SPD:'»',HP:'♥',CDR:'⌁',DRAW:'✦',CORE:'◆',SAVE:'⊕',DASH:'➤',LUCK:'✧',ARM:'⬡',ARC:'⌁'})[k]||'◇'}
function rarityClass(c){return `rarity-R${Math.max(1,Math.min(5,c?.rarity||1))}`}
function renderEquipSlots(){document.querySelectorAll('.equipSlot').forEach((el,slot)=>{const uid=state.equippedCharms[slot],c=proceduralCharmByUid(uid);el.className=`equipSlot${c?' filled '+rarityClass(c):''}`;if(c){el.innerHTML=`<span class="equipIndex">0${slot+1}</span><strong>${c.name}</strong><small>${charmAffixText(c)} · CLICK TO UNEQUIP</small>`;el.onclick=()=>unequipSlot(slot);el.draggable=true;el.ondragstart=e=>e.dataTransfer.setData('text/charm-uid',c.uid)}else{el.innerHTML=`<span class="equipIndex">0${slot+1}</span><strong>EMPTY SLOT</strong><small>DROP CHARM HERE</small>`;el.onclick=null;el.draggable=false}el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();const uid=e.dataTransfer.getData('text/charm-uid');if(uid)equipCharmToSlot(uid,slot)}})}
function v121RenderInventory(){const grid=document.getElementById('inventoryGrid');if(!grid)return;grid.innerHTML='';const sorted=[...state.inventory].sort((a,b)=>b.rarity-a.rarity||a.name.localeCompare(b.name));const slotCount=Math.max(INVENTORY_VISIBLE_MIN,Math.ceil(sorted.length/9)*9);for(let i=0;i<slotCount;i++){const c=sorted[i],el=document.createElement('button');if(!c){el.className='mcSlot empty';el.disabled=true;grid.appendChild(el);continue}const equipped=equippedSlotOf(c.uid);el.className=`mcSlot ${rarityClass(c)}${state.selectedInventoryCharm===c.uid?' selected':''}`;el.draggable=true;el.dataset.uid=c.uid;el.title=`${c.name}\n${CHARM_RARITY_LABEL[c.rarity]} · ${charmAffixText(c)}`;el.innerHTML=`<span class="slotFx">${c.affixes.length}FX</span><span class="slotGlyph">${charmGlyph(c)}</span><span class="slotRank">R${c.rarity}${equipped>=0?' · E'+(equipped+1):''}</span>`;el.onclick=()=>{state.selectedInventoryCharm=c.uid;v121RenderInventory();v121RenderDetail(c)};el.ondblclick=()=>{const current=equippedSlotOf(c.uid);if(current>=0)unequipCharmUid(c.uid);else equipCharmToSlot(c.uid,state.equippedCharms.length<2?state.equippedCharms.length:1)};el.ondragstart=e=>e.dataTransfer.setData('text/charm-uid',c.uid);grid.appendChild(el)}document.getElementById('inventoryText').textContent=`${state.inventory.length} CHARMS · ${slotCount} SLOTS`}
function v121RenderDetail(c){const el=document.getElementById('itemDetail');if(!el)return;if(!c){el.className='inventoryDetail';el.innerHTML='<strong>SELECT AN ITEM</strong><small>正方形スロットをクリックすると詳細を表示します。</small>';return}const equipped=equippedSlotOf(c.uid);el.className=`inventoryDetail ${rarityClass(c)}`;el.innerHTML=charmDetailHtml(c)+`<div class="muted" style="margin-top:12px">UID ${c.uid}<br>${equipped>=0?'EQUIPPED IN SLOT '+(equipped+1):'NOT EQUIPPED'}</div><div class="detailEquipGrid"><button id="equipTo1" class="btn"><strong>SLOT 1</strong><small>${state.equippedCharms[0]===c.uid?'EQUIPPED':'EQUIP'}</small></button><button id="equipTo2" class="btn"><strong>SLOT 2</strong><small>${state.equippedCharms[1]===c.uid?'EQUIPPED':'EQUIP'}</small></button></div>${equipped>=0?'<button id="unequipSelected" class="btn detailUnequip"><strong>UNEQUIP</strong><small>装備から外す</small></button>':''}`;document.getElementById('equipTo1').onclick=()=>equipCharmToSlot(c.uid,0);document.getElementById('equipTo2').onclick=()=>equipCharmToSlot(c.uid,1);document.getElementById('unequipSelected')?.addEventListener('click',()=>unequipCharmUid(c.uid))}
function renderSkillOnlyV121(){const sg=document.getElementById('skillGrid');if(!sg)return;sg.innerHTML='';for(const s of DATA.skills){const el=document.createElement('button');el.className='card'+(state.equippedSkill===s.id?' selected':'');el.innerHTML=`<strong>${s.name}</strong><small>${s.description}<br>CD ${s.cooldown}s</small>`;el.onclick=()=>{state.equippedSkill=s.id;save('raidqix.skill',s.id);renderLoadoutV121()};sg.appendChild(el)}}
function renderLoadoutV121(){renderSkillOnlyV121();renderEquipSlots();v121RenderInventory();v121RenderDetail(proceduralCharmByUid(state.selectedInventoryCharm)||null);renderFusionSlots();updateFusionStatus()}
renderLoadout=renderLoadoutV121;
const _v100FuseFive121=typeof fuseFive==='function'?fuseFive:null;if(_v100FuseFive121){fuseFive=function(){_v100FuseFive121();state.equippedCharms=state.equippedCharms.filter(uid=>proceduralCharmByUid(uid));saveEquipped();renderLoadoutV121()}}
charmDefs=function(){return state.equippedCharms.map(proceduralCharmByUid).filter(Boolean)};
renderLoadoutV121();

(function bootstrapV122(){
  const screen=document.getElementById('loadoutScreen');
  if(!screen||document.getElementById('loadoutTabGear'))return;
  screen.innerHTML=`<div class="panel loadoutPanel"><div class="loadoutHeader"><div><div class="eyebrow">PLAYER BUILD</div><div class="title" style="font-size:28px">LOADOUT</div></div><div class="loadoutTabs"><button id="loadoutTabGear" class="loadoutTab active">GEAR</button><button id="loadoutTabFusion" class="loadoutTab">FUSION</button></div></div><div id="loadoutGearView" class="loadoutView active"><aside class="gearLeft"><section class="loadBlock"><h3>SKILL</h3><div id="skillGrid" class="skillCompactGrid"></div></section><section class="loadBlock"><h3>CHARM SLOTS</h3><div id="charmGrid" class="equipStrip"><button class="equipSlot" data-equip-slot="0"><span class="equipIndex">01</span><strong>EMPTY</strong><small>DROP / CLICK TO REMOVE</small></button><button class="equipSlot" data-equip-slot="1"><span class="equipIndex">02</span><strong>EMPTY</strong><small>DROP / CLICK TO REMOVE</small></button></div></section></aside><main class="gearCenter"><section class="loadBlock inventoryBlock"><div class="loadBlockHeader"><h3>INVENTORY</h3><div id="inventoryText" class="muted"></div></div><div id="inventoryGrid" class="mcInventoryGrid"></div></section></main><aside id="itemDetail" class="inventoryDetail"><strong>SELECT AN ITEM</strong><small>クリックで詳細。ダブルクリックで装備/解除。</small></aside></div><div id="loadoutFusionView" class="loadoutView"><div class="fusionLayout"><section class="loadBlock"><div class="loadBlockHeader"><h3>FUSION MATERIALS</h3><div class="muted">同レアリティ5個</div></div><div id="fusionSlots" class="fusionBigSlots"><div class="card fusionSlot" data-slot="0"><strong>DROP</strong><small>1</small></div><div class="card fusionSlot" data-slot="1"><strong>DROP</strong><small>2</small></div><div class="card fusionSlot" data-slot="2"><strong>DROP</strong><small>3</small></div><div class="card fusionSlot" data-slot="3"><strong>DROP</strong><small>4</small></div><div class="card fusionSlot" data-slot="4"><strong>DROP</strong><small>5</small></div></div><button id="fusionButton" class="btn fusionAction"><strong>FUSE 5 → NEXT RARITY</strong><small>素材5個を消費</small></button><div id="fusionStatus" class="muted" style="margin-top:10px">5個ドラッグしてセットしてください</div></section><section class="loadBlock fusionInventoryBlock"><div class="loadBlockHeader"><h3>INVENTORY</h3><div class="muted">ドラッグして左へ</div></div><div id="fusionInventoryGrid" class="mcInventoryGrid fusionInventoryGrid"></div></section></div></div><button class="btn loadoutBack" data-open="titleScreen">BACK</button></div>`;
  const st=document.createElement('style');st.textContent=`.loadoutPanel{width:min(1240px,94vw)!important;height:min(760px,92vh)!important;overflow:hidden!important;padding:24px!important;display:grid!important;grid-template-rows:auto 1fr auto!important;gap:14px}.loadoutHeader{display:flex;align-items:flex-end;justify-content:space-between;border-bottom:1px solid #2b3540;padding-bottom:12px}.loadoutTabs{display:flex;gap:6px}.loadoutTab{border:1px solid #34404b;background:#080d13;color:#9bacbb;padding:9px 18px;cursor:pointer;font-size:11px;letter-spacing:2px}.loadoutTab.active{background:#16212b;color:#fff;border-color:#5deaff}.loadoutView{display:none;min-height:0}.loadoutView.active{display:block}#loadoutGearView.active{display:grid;grid-template-columns:250px minmax(0,1fr) 300px;gap:14px;min-height:0}.gearLeft{display:flex;flex-direction:column;gap:14px;min-height:0}.loadBlock{border:1px solid #2a3541;background:#0a1017;padding:14px;min-height:0}.loadBlock h3,.loadBlockHeader h3{margin:0;font-size:10px;letter-spacing:3px;color:#91a1af}.loadBlockHeader{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}.skillCompactGrid{display:grid;gap:7px}.skillCompactGrid .card{padding:10px}.skillCompactGrid .card strong{font-size:12px}.skillCompactGrid .card small{font-size:9px}.equipStrip{display:grid;gap:8px}.inventoryBlock{height:100%;display:flex;flex-direction:column}.mcInventoryGrid{grid-template-columns:repeat(8,minmax(0,1fr))!important;overflow-y:auto!important}.loadoutBack{margin:0!important;width:120px!important}.fusionLayout{display:grid;grid-template-columns:420px minmax(0,1fr);gap:14px;height:100%}.fusionBigSlots{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:14px}.fusionAction{width:100%;margin-top:14px}.fusionInventoryBlock{display:flex;flex-direction:column}.fusionInventoryGrid{flex:1}`;document.head.appendChild(st);
  const loader=document.createElement('script');loader.src='game-v122.js';document.body.appendChild(loader);
})();
