// RAID QIX v1.2.0 runtime patch
// Audio polish, compact title UI and fixed 16:9 display modes.

(function bootstrapV12Ui(){
  const title=document.getElementById('titleScreen');
  if(title&&!document.querySelector('.v12Header')){
    title.innerHTML=`<div class="titleDeck"><aside class="titleRail"><div class="railLogo">RAID<br>QIX<small>CO-OP TERRITORY RAID / SYSTEM 1.2</small></div><button id="titleBossMode" class="railButton active"><strong>BOSS MODE</strong><small>SELECTED ENCOUNTER</small></button><button id="titleRandomMode" class="railButton"><strong>RANDOM BOSS</strong><small>ENDLESS PROCEDURAL RAID</small></button><button class="railButton" data-open="loadoutScreen"><strong>LOADOUT</strong><small>CHARM / SKILL / FUSION</small></button><button class="railButton" data-open="settingsScreen"><strong>SETTINGS</strong><small>DISPLAY / AUDIO / CONTROL</small></button></aside><main class="titleRight"><header class="v12Header"><div><div class="eyebrow">RAID PROGRAM</div><h2 id="titleModeName">BOSS MODE</h2></div><div class="eyebrow" style="text-align:right">STEAM / ONLINE<br><span style="color:#59e7ff">READY</span></div></header><div class="v12Content"><section class="v12Card" id="titleBossSection"><h3>ENCOUNTER SELECT</h3><div id="titleBossGrid" class="titleBossGrid"></div></section><section class="v12Card v12TrackCard"><h3>BOSS TRACKLIST / SOUNDCLOUD</h3><div class="trackInput"><input id="scUrlInput" placeholder="SOUNDCLOUD TRACK URL"><input id="scBpmInput" type="number" min="40" max="240" value="120"><button id="scAddTrack" class="v12MiniBtn">ADD</button></div><div id="scTrackList" class="trackList"></div><div id="scNowPlaying" class="nowPlaying">NO TRACK PLAYING</div></section><section class="v12Card v12Participants"><h3>PARTICIPANTS</h3><div id="titleMembers"><div class="muted">ROOM NOT CREATED</div></div></section><section class="v12Card"><h3>MODE STATUS</h3><div id="titleModeInfo" style="font-size:12px;line-height:1.65">固定ボスを選択してレイド。</div></section></div><div class="v12Bottom"><button id="titleStartRaid" class="railButton v12Start" style="border-left-color:#ffe15a"><strong>START RAID</strong><small>AUTO CREATE ROOM</small></button><div class="v12SessionMini">SESSION <span id="titleLobbyCode" class="sessionCode">NO ROOM</span><div class="v12SessionBtns"><button id="titleCreateRoom" class="v12MiniBtn">ROOM</button><button id="titleInvite" class="v12MiniBtn">INVITE</button><button id="titleCopyCode" class="v12MiniBtn">COPY</button><input id="titleJoinCode" placeholder="CODE" style="width:108px;background:#05080c;color:#fff;border:1px solid #31404c;padding:5px;font-size:9px"><button id="titleJoinRoom" class="v12MiniBtn">JOIN</button></div></div></div></main></div>`;
  }
  if(!document.getElementById('displayMode')){
    const anchor=document.getElementById('screenShake')?.closest('.setting');
    if(anchor){const wrap=document.createElement('div');wrap.className='setting';wrap.innerHTML=`<label>DISPLAY MODE</label><select id="displayMode" style="width:100%;padding:12px;background:#070a10;border:1px solid #353b48;color:#fff"><option value="960x540">WINDOW 960 × 540</option><option value="1280x720">WINDOW 1280 × 720</option><option value="1600x900">WINDOW 1600 × 900</option><option value="1920x1080">WINDOW 1920 × 1080</option><option value="fullscreen">FULLSCREEN</option></select><div class="muted" style="margin-top:6px;font-size:10px">16:9 presets only. Manual resize is disabled.</div>`;anchor.parentElement.insertBefore(wrap,anchor)}
  }
  if(!document.getElementById('v12RuntimeStyle')){
    const st=document.createElement('style');st.id='v12RuntimeStyle';st.textContent=`#titleScreen{overflow:hidden}.titleDeck{width:100vw;height:100vh;display:grid;grid-template-columns:minmax(250px,31vw) 1fr;background:#080d13;overflow:hidden}.titleRail{padding:3vh 2.3vw;background:#0d141b;border-right:1px solid #26303b;overflow:hidden}.railLogo{font-size:clamp(30px,5vw,54px);font-weight:900;letter-spacing:8px;line-height:.9;margin-bottom:5vh}.railLogo small{display:block;font-size:9px;letter-spacing:4px;opacity:.4;margin-top:8px}.railButton{width:100%;border:0;border-left:9px solid #127c88;background:#05080b;color:#fff;margin-bottom:1.4vh;padding:1.7vh 22px;text-align:left;cursor:pointer}.railButton strong{display:block;font-size:clamp(14px,1.7vw,20px);letter-spacing:2px}.railButton small{display:block;margin-top:5px;opacity:.46;font-size:10px}.railButton.active{border-left-color:#52eaff;background:#111d25}.titleRight{padding:3vh 3vw;overflow:hidden;position:relative;background:radial-gradient(circle at 80% 15%,rgba(81,226,255,.08),transparent 34%),#080d13}.v12Header{display:flex;justify-content:space-between;height:12%}.v12Header h2{margin:0;font-size:clamp(22px,3vw,38px);letter-spacing:6px}.v12Content{height:77%;display:grid;grid-template-columns:.88fr 1.12fr;grid-template-rows:1fr 1fr;gap:14px}.v12Card{border:1px solid #2a3541;background:#0c131b;padding:16px;overflow:hidden;min-height:0}.v12Card h3{margin:0 0 10px;font-size:10px;letter-spacing:3px;color:#8fa1b1}.v12TrackCard,.v12Participants{display:flex;flex-direction:column}.trackList,#titleMembers{flex:1;overflow:hidden}.trackInput{display:grid;grid-template-columns:1fr 64px 58px;gap:7px}.trackInput input{min-width:0;padding:8px;background:#05080c;color:#fff;border:1px solid #34404c}.v12Bottom{position:absolute;left:3vw;right:3vw;bottom:2vh;height:9%;display:flex;align-items:flex-end;justify-content:space-between;border-top:1px solid #26313b;padding-top:9px}.v12SessionMini{text-align:right;font-size:9px;letter-spacing:2px;color:#8394a3}.v12SessionBtns{display:flex;gap:5px;margin-top:5px}.v12MiniBtn{border:1px solid #31404c;background:#070b10;color:#dbe7ef;padding:5px 8px;font-size:9px;cursor:pointer}.v12Start{min-width:250px;margin:0}.titleBossGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;height:calc(100% - 22px);overflow:hidden}.titleBossGrid .card{padding:8px}`;document.head.appendChild(st)
  }
})();

Object.assign(state,{lossAudioActive:false,seContext:null,seMaster:null,muffleContext:null,muffleSource:null,beatPulse:state.beatPulse||0});

const displayModeEl=document.getElementById('displayMode');
(async()=>{try{const m=await window.raidAPI?.getDisplayMode?.();if(m&&displayModeEl)displayModeEl.value=m}catch{}})();
displayModeEl?.addEventListener('change',()=>window.raidAPI?.setDisplayMode?.(displayModeEl.value));

function master01(){return Math.max(0,Math.min(1,(Number(state.settings.volume)||0)/100))}
function bgmVol(){return Math.round(Math.max(0,Math.min(100,state.bgmVolume*master01())))}
function seVol(){return Math.max(0,Math.min(1,(state.seVolume/100)*master01()))}
function setScVol(v){try{ensureSoundCloudWidget()?.setVolume(Math.max(0,Math.min(100,Math.round(v))))}catch{}}

function seCtx(){if(state.seContext)return state.seContext;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;const c=new AC(),g=c.createGain();g.gain.value=seVol()*.28;g.connect(c.destination);state.seContext=c;state.seMaster=g;return c}
function tone(f,e,d=.12,type='square',gain=.18,delay=0){const c=seCtx();if(!c)return;if(c.state==='suspended')c.resume().catch(()=>{});state.seMaster.gain.value=seVol()*.28;const t=c.currentTime+delay,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(e)o.frequency.exponentialRampToValueAtTime(Math.max(20,e),t+d);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(gain,t+.008);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(state.seMaster);o.start(t);o.stop(t+d+.02)}
function playSe(n){if(n==='laser'){tone(760,250,.2,'sawtooth');tone(1180,520,.12,'square',.08,.025)}else if(n==='aoe'){tone(150,60,.18,'square',.22)}else if(n==='hurt'){tone(310,75,.16,'square',.24)}else if(n==='capture'){tone(440,null,.07,'square',.16);tone(660,null,.08,'square',.16,.065);tone(880,null,.09,'square',.14,.13)}else if(n==='skill'){tone(520,980,.13,'square',.16);tone(780,1280,.1,'triangle',.11,.045)}else if(n==='bosskill'){[330,440,660,880,1100].forEach((f,i)=>tone(f,null,.13,i<3?'square':'triangle',.16,i*.075))}}

const _sweep12=updateSweepLasers;updateSweepLasers=function(dt,a=true){const b=new Map(state.sweepLasers.map(l=>[l.id,l.warning]));_sweep12(dt,a);for(const l of state.sweepLasers){if(a&&b.get(l.id)>0&&l.warning<=0&&!l._se){l._se=true;playSe('laser')}}};
const _aoe12=updateTelegraphs;updateTelegraphs=function(dt,a=true){const b=new Map(state.telegraphs.map(t=>[t.id,t.warning]));_aoe12(dt,a);if(a)for(const t of state.telegraphs){if(b.get(t.id)>0&&t.warning<=0&&!t._se){t._se=true;playSe('aoe')}}};
const _hit12=playerHit;playerHit=function(){const hp=playerHP;_hit12();if(playerHP<hp){playSe('hurt');if(playerHP<=0)beginLossAudio()}};
const _line12=finishLine;finishLine=function(){const ok=player.drawing&&player.line.length>4;_line12();if(ok)playSe('capture')};
const _skill12=useSkill;useSkill=function(){const cd=state.skillCooldown;_skill12();if(cd<=0&&state.skillCooldown>0)playSe('skill')};
const _win12=winRaid;winRaid=function(b=false){const v=state.victory;_win12(b);if(!v&&state.victory)playSe('bosskill')};

function forceStart(w,delay=0){clearTimeout(state.music.scheduled);state.music.scheduled=setTimeout(()=>{try{w.seekTo(0);setTimeout(()=>{w.setVolume(bgmVol());w.play();state.music.positionMs=0;state.music.lastProgressAt=performance.now()},70)}catch{}},Math.max(0,delay))}
const _widget12=ensureSoundCloudWidget;ensureSoundCloudWidget=function(){const w=_widget12();if(w&&!w._v12Loop){w._v12Loop=true;w.bind(SC.Widget.Events.FINISH,()=>{if(state.mode==='raid'&&!state.gameOver){try{w.seekTo(0);setTimeout(()=>{w.setVolume(bgmVol());w.play()},60)}catch{}}})}return w};
loadSoundCloudUrl=function(track,delay=700){const w=ensureSoundCloudWidget(),iframe=document.getElementById('soundcloudWidget');if(!iframe)return;state.music.url=track.url;state.music.bpm=track.bpm||120;if(!w){iframe.src=`https://w.soundcloud.com/player/?url=${encodeURIComponent(track.url)}&auto_play=false`;return}w.load(track.url,{auto_play:false,show_artwork:false,show_comments:false,buying:false,sharing:false,download:false,callback:()=>forceStart(w,delay)})};
playSoundCloudTrack=function(track,{delayMs=800,broadcast=true}={}){if(!track)return;stopLossMuffle(true);loadSoundCloudUrl(track,delayMs);if(broadcast&&state.isHost&&state.multiplayer)sendNet({type:'bgm-sync',track,delayMs})};
const _startRaid12=startRaid;startRaid=function(mp,broadcast){if(state.isHost){const t=chooseBossTrack();if(t)playSoundCloudTrack(t,{delayMs:850,broadcast:true})}return _startRaid12(mp,broadcast)};

function startMuffle(){if(state.muffleContext)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const c=new AC(),o=c.createOscillator(),f=c.createBiquadFilter(),g=c.createGain();o.type='sawtooth';o.frequency.value=62;f.type='lowpass';f.frequency.value=260;g.gain.value=.001;o.connect(f);f.connect(g);g.connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.018,c.currentTime+1.1);state.muffleContext=c;state.muffleSource=o}
function beginLossAudio(){if(state.lossAudioActive)return;state.lossAudioActive=true;startMuffle();const start=bgmVol(),at=performance.now();const tick=()=>{if(!state.lossAudioActive)return;const t=Math.min(1,(performance.now()-at)/1350);setScVol(start*(1-.66*t));if(t<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)}
function stopLossMuffle(restore=false){state.lossAudioActive=false;if(state.muffleContext){try{state.muffleContext.close()}catch{}state.muffleContext=null;state.muffleSource=null}if(restore)setScVol(bgmVol())}
function fadeTitle(){const w=ensureSoundCloudWidget();if(!w){stopLossMuffle(false);return}const start=bgmVol(),at=performance.now();const tick=()=>{const t=Math.min(1,(performance.now()-at)/850);setScVol(start*(1-t));if(t<1)requestAnimationFrame(tick);else{try{w.pause();w.seekTo(0)}catch{}stopLossMuffle(false)}};requestAnimationFrame(tick)}
const _open12=openScreen;openScreen=function(id){if(id==='titleScreen'&&state.music.url)fadeTitle();_open12(id)};

const bgm=document.getElementById('bgmVolume'),se=document.getElementById('seVolume'),master=document.getElementById('volume');
if(bgm)bgm.oninput=()=>{state.bgmVolume=Number(bgm.value);save('raidqix.bgmVolume',state.bgmVolume);document.getElementById('bgmVolLabel').textContent=state.bgmVolume;setScVol(bgmVol())};
if(se)se.oninput=()=>{state.seVolume=Number(se.value);save('raidqix.seVolume',state.seVolume);document.getElementById('seVolLabel').textContent=state.seVolume;if(state.seMaster)state.seMaster.gain.value=seVol()*.28};
master?.addEventListener('input',()=>{setScVol(bgmVol());if(state.seMaster)state.seMaster.gain.value=seVol()*.28});

function bindTitleV12(){document.querySelectorAll('[data-open]').forEach(el=>el.onclick=()=>openScreen(el.dataset.open));document.getElementById('titleBossMode').onclick=()=>{setTitleMode('boss');renderTitleBosses()};document.getElementById('titleRandomMode').onclick=()=>setTitleMode('random');document.getElementById('titleCreateRoom').onclick=async()=>{const s=await window.raidAPI.createLobby({maxMembers:4});state.isHost=true;applySteamState(s)};document.getElementById('titleJoinRoom').onclick=async()=>{const id=document.getElementById('titleJoinCode').value.trim();if(id)applySteamState(await window.raidAPI.joinLobby(id))};document.getElementById('titleInvite').onclick=async()=>{if(!state.titleLobbyId)applySteamState(await window.raidAPI.createLobby({maxMembers:4}));await window.raidAPI.inviteLobby?.()};document.getElementById('titleCopyCode').onclick=()=>state.titleLobbyId&&navigator.clipboard?.writeText(state.titleLobbyId);document.getElementById('scAddTrack').onclick=()=>{const url=document.getElementById('scUrlInput').value.trim(),bpm=Math.max(40,Math.min(240,Number(document.getElementById('scBpmInput').value)||120));if(!validSoundCloudUrl(url))return;state.soundcloudPlaylist.push({id:'sc_'+Date.now().toString(36),url,bpm});save('raidqix.soundcloudPlaylist',state.soundcloudPlaylist);document.getElementById('scUrlInput').value='';renderTrackList()};document.getElementById('titleStartRaid').onclick=async()=>{if(!state.titleLobbyId){const s=await window.raidAPI.createLobby({maxMembers:4});state.isHost=true;applySteamState(s)}if(!state.isHost)return;state.titleMode==='random'?titleStartRandomMode():titleStartBossMode()}}
renderTitleBosses();renderTrackList();setTitleMode(state.titleMode||'boss');bindTitleV12();refreshSteam();
