const DATA = window.RAID_DATA;
const canvas = document.getElementById('game');
const displayCtx = canvas.getContext('2d', { alpha:false });
const sceneCanvas = document.createElement('canvas');
const sceneCtx = sceneCanvas.getContext('2d', { alpha:false });
const pixelCanvas = document.createElement('canvas');
const pixelCtx = pixelCanvas.getContext('2d', { alpha:false });

const LOGICAL_W = 960;
const LOGICAL_H = 540;
const PIXEL_W = 320;
const PIXEL_H = 180;
const GRID = 6;

sceneCanvas.width = LOGICAL_W;
sceneCanvas.height = LOGICAL_H;
pixelCanvas.width = PIXEL_W;
pixelCanvas.height = PIXEL_H;
sceneCtx.imageSmoothingEnabled = false;
pixelCtx.imageSmoothingEnabled = false;
displayCtx.imageSmoothingEnabled = false;

const world = { x:76, y:68, w:808, h:402 };
let cols = 0, rows = 0, grid = [];
const keys = {};

const state = {
  mode:'menu', bossId:DATA.bosses[0].id, boss:null, projectiles:[], effects:[], relics:[],
  area:0, relicCount:0, damage:0, gameOver:false, victory:false,
  skillCooldown:0, buffTimer:0, iframeTimer:0,
  inventory:load('raidqix.inventory',['runner-coil','spare-heart','cold-clock']),
  equippedSkill:load('raidqix.skill','phase-dash'),
  equippedCharms:load('raidqix.charms',['runner-coil','spare-heart']),
  settings:load('raidqix.settings',{volume:80,screenShake:true,pixelMode:true}),
  multiplayer:false, isHost:false, members:[], localSteamId:'local', remotePlayers:new Map(),
  netPlayerTimer:0, netWorldTimer:0, seraphLaserAngle:0, seraphTeleportTimer:5, seraphPulse:0
};

const player={x:0,y:0,r:7,baseSpeed:180,drawing:false,line:[],lastSafeX:0,lastSafeY:0,dx:0,dy:0};
let playerHP=3,playerMaxHP=3,deathSaveCharges=0;

function load(key,fallback){try{const v=localStorage.getItem(key);return v?JSON.parse(v):fallback}catch{return fallback}}
function save(key,value){localStorage.setItem(key,JSON.stringify(value))}
function bossDef(){return DATA.bosses.find(b=>b.id===state.bossId)||DATA.bosses[0]}
function skillDef(){return DATA.skills.find(s=>s.id===state.equippedSkill)||DATA.skills[0]}
function charmDefs(){return state.equippedCharms.map(id=>DATA.charms.find(c=>c.id===id)).filter(Boolean)}
function modifiers(){const m={moveSpeedMultiplier:1,drawingSpeedMultiplier:1,maxHpAdd:0,cooldownMultiplier:1,relicDamageMultiplier:1,deathSaveCharges:0};for(const c of charmDefs())for(const[k,v]of Object.entries(c.modifiers||{})){if(k.endsWith('Multiplier'))m[k]*=v;else m[k]+=v}return m}

function resizeDisplay(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.floor(innerWidth*dpr));canvas.height=Math.max(1,Math.floor(innerHeight*dpr));canvas.style.width='100vw';canvas.style.height='100vh';displayCtx.imageSmoothingEnabled=false}
addEventListener('resize',resizeDisplay);
function buildGrid(){cols=Math.floor(world.w/GRID)+1;rows=Math.floor(world.h/GRID)+1;grid=[];for(let y=0;y<rows;y++){grid[y]=[];for(let x=0;x<cols;x++)grid[y][x]=(x===0||y===0||x===cols-1||y===rows-1)?1:0}}
function worldToGrid(x,y){return{x:Math.round((x-world.x)/GRID),y:Math.round((y-world.y)/GRID)}}
function insideGrid(x,y){return x>=0&&y>=0&&x<cols&&y<rows}
function isSafeWorld(x,y){const p=worldToGrid(x,y);return!insideGrid(p.x,p.y)||grid[p.y][p.x]===1}
function cloneGrid(){return grid.map(row=>row.slice())}
function setGrid(next){if(!Array.isArray(next)||!next.length||!Array.isArray(next[0]))return;grid=next.map(r=>r.map(v=>v?1:0));rows=grid.length;cols=grid[0].length;updateArea()}
function mergeGrid(incoming){if(!Array.isArray(incoming)||incoming.length!==rows)return;for(let y=0;y<rows;y++)for(let x=0;x<cols;x++)if(incoming[y]?.[x])grid[y][x]=1;updateArea()}

const coreTypes=[
{name:'ORB',color:'#55e8ff',damage:70},{name:'CROWN',color:'#ffe066',damage:120},{name:'CORE',color:'#ff64d5',damage:200},{name:'SHARD',color:'#9e8cff',damage:50},
{name:'SUN',color:'#ff934d',damage:150},{name:'VOID',color:'#69ff8d',damage:90},{name:'STAR',color:'#ffffff',damage:180},{name:'REACTOR',color:'#ff527c',damage:250}
];
function resetPlayer(){const m=modifiers();player.x=world.x+world.w*.5;player.y=world.y+world.h-5;player.lastSafeX=player.x;player.lastSafeY=player.y;player.drawing=false;player.line=[];playerMaxHP=3+m.maxHpAdd;playerHP=playerMaxHP;deathSaveCharges=m.deathSaveCharges;state.skillCooldown=0;state.buffTimer=0;state.iframeTimer=0}
function resetBoss(){const d=bossDef(),integrity=coreTypes.reduce((a,c)=>a+c.damage,0);state.boss={x:world.x+world.w*.5,y:world.y+world.h*.42,r:d.number===3?44:34,hp:integrity,maxHp:integrity,angle:0,attackTimer:d.number===2?1.5:1};state.seraphLaserAngle=0;state.seraphTeleportTimer=5;state.seraphPulse=0}
function spawnRelics(){state.relics=[];const placed=[],marginX=world.w*.17,marginY=world.h*.15,minX=world.x+marginX,maxX=world.x+world.w-marginX,minY=world.y+marginY,maxY=world.y+world.h-marginY,minSpacing=84;for(const type of coreTypes){let x,y,tries=0;do{x=minX+Math.random()*(maxX-minX);y=minY+Math.random()*(maxY-minY);tries++}while(tries<250&&(Math.hypot(x-state.boss.x,y-state.boss.y)<105||placed.some(p=>Math.hypot(x-p.x,y-p.y)<minSpacing)));placed.push({x,y});state.relics.push({x,y,r:9,type:{...type},taken:false,phase:Math.random()*Math.PI*2})}}
function remainingCores(){return state.relics.filter(r=>!r.taken).length}
function resetGame(){state.projectiles=[];state.effects=[];state.remotePlayers.clear();state.area=0;state.relicCount=0;state.damage=0;state.gameOver=false;state.victory=false;buildGrid();resetPlayer();resetBoss();spawnRelics();updateHud()}

addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(e.key.toLowerCase()))e.preventDefault();if(e.key.toLowerCase()==='e')useSkill()});
addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function currentSpeed(){const m=modifiers();return player.baseSpeed*m.moveSpeedMultiplier*(player.drawing?m.drawingSpeedMultiplier:1)*(state.buffTimer>0?1.45:1)}
function movePlayer(dt){let dx=0,dy=0;if(keys.w||keys.arrowup)dy--;if(keys.s||keys.arrowdown)dy++;if(keys.a||keys.arrowleft)dx--;if(keys.d||keys.arrowright)dx++;if(dx||dy){const l=Math.hypot(dx,dy);dx/=l;dy/=l}player.dx=dx;player.dy=dy;const ox=player.x,oy=player.y,s=currentSpeed();player.x+=dx*s*dt;player.y+=dy*s*dt;player.x=Math.max(world.x,Math.min(world.x+world.w,player.x));player.y=Math.max(world.y,Math.min(world.y+world.h,player.y));const safe=isSafeWorld(player.x,player.y);if(safe){player.lastSafeX=player.x;player.lastSafeY=player.y}if(!player.drawing&&!safe){player.drawing=true;player.line=[{x:ox,y:oy},{x:player.x,y:player.y}]}if(player.drawing){const last=player.line[player.line.length-1];if(Math.hypot(player.x-last.x,player.y-last.y)>3)player.line.push({x:player.x,y:player.y});if(safe&&player.line.length>4)finishLine()}}
function useSkill(){if(state.mode!=='raid'||state.gameOver||state.skillCooldown>0)return;const s=skillDef(),m=modifiers();if(s.type==='dash'){let dx=player.dx,dy=player.dy;if(!dx&&!dy)dy=-1;player.x=Math.max(world.x,Math.min(world.x+world.w,player.x+dx*90));player.y=Math.max(world.y,Math.min(world.y+world.h,player.y+dy*90));state.iframeTimer=.6}if(s.type==='heal')playerHP=Math.min(playerMaxHP,playerHP+1);if(s.type==='speed')state.buffTimer=5;state.skillCooldown=s.cooldown*m.cooldownMultiplier;state.effects.push({x:player.x,y:player.y,r:14,life:.8,color:'#69ff8d'})}
function finishLine(){if(!player.drawing)return;player.line.push({x:player.x,y:player.y});captureArea();player.drawing=false;player.line=[]}
function captureArea(){for(let i=1;i<player.line.length;i++){const a=worldToGrid(player.line[i-1].x,player.line[i-1].y),b=worldToGrid(player.line[i].x,player.line[i].y),steps=Math.max(Math.abs(b.x-a.x),Math.abs(b.y-a.y),1);for(let s=0;s<=steps;s++){const t=s/steps,gx=Math.round(a.x+(b.x-a.x)*t),gy=Math.round(a.y+(b.y-a.y)*t);if(insideGrid(gx,gy))grid[gy][gx]=1}}const start=worldToGrid(state.boss.x,state.boss.y),visited=new Uint8Array(cols*rows),q=[];if(insideGrid(start.x,start.y)){q.push([start.x,start.y]);visited[start.y*cols+start.x]=1}let h=0;while(h<q.length){const[x,y]=q[h++];for(const[dX,dY]of[[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dX,ny=y+dY;if(!insideGrid(nx,ny))continue;const idx=ny*cols+nx;if(visited[idx]||grid[ny][nx]!==0)continue;visited[idx]=1;q.push([nx,ny])}}for(let y=1;y<rows-1;y++)for(let x=1;x<cols-1;x++)if(grid[y][x]===0&&!visited[y*cols+x])grid[y][x]=1;collectRelics();updateArea();state.effects.push({x:player.x,y:player.y,r:15,life:.8,color:'#55e8ff'});if(state.multiplayer){if(state.isHost)sendNet({type:'grid-state',grid:cloneGrid()});else sendNet({type:'capture-state',grid:cloneGrid()})}}
function collectRelics(){const m=modifiers();for(const r of state.relics){if(r.taken)continue;if(isSafeWorld(r.x,r.y)){r.taken=true;state.relicCount++;const dmg=Math.round(r.type.damage*m.relicDamageMultiplier);state.damage+=dmg;const left=remainingCores();if(state.multiplayer&&!state.isHost)sendNet({type:'core-destroyed',coreName:r.type.name,amount:dmg,remaining:left});else state.boss.hp=Math.max(left>0?1:0,state.boss.hp-dmg);state.effects.push({x:r.x,y:r.y,r:20,life:1,color:r.type.color});if(left===0){state.boss.hp=0;winRaid(true);return}}}}
function updateArea(){let safe=0,total=0;for(let y=1;y<rows-1;y++)for(let x=1;x<cols-1;x++){total++;if(grid[y][x]===1)safe++}state.area=total?safe/total*100:0}
function playerHit(){if(state.gameOver||state.iframeTimer>0)return;playerHP--;if(playerHP<=0&&deathSaveCharges>0){deathSaveCharges--;playerHP=1}state.effects.push({x:player.x,y:player.y,r:10,life:.7,color:'#ff315c'});player.x=player.lastSafeX;player.y=player.lastSafeY;player.drawing=false;player.line=[];state.iframeTimer=.8;if(playerHP<=0){playerHP=0;if(state.multiplayer)sendNet({type:'player-dead'});state.gameOver=true;setTimeout(()=>openScreen('titleScreen'),1000)}}

function spawnBullet(angle,speed,size,opts={}){state.projectiles.push({x:state.boss.x,y:state.boss.y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,r:size,ricochet:!!opts.ricochet,bounces:0,maxBounces:opts.maxBounces||5,life:opts.life??12,color:opts.color||'#ff587a'})}
function radialBurst(count,speed=70){for(let i=0;i<count;i++)spawnBullet(state.boss.angle+i*Math.PI*2/count,speed,6)}
function aimedBurst(count=5,spread=.12,speed=95){const a=Math.atan2(player.y-state.boss.y,player.x-state.boss.x);for(let i=-(count-1)/2;i<=(count-1)/2;i++)spawnBullet(a+i*spread,speed,5)}
function linePointDistance(px,py,x1,y1,x2,y2){const dx=x2-x1,dy=y2-y1,l2=dx*dx+dy*dy;if(!l2)return Math.hypot(px-x1,py-y1);const t=Math.max(0,Math.min(1,((px-x1)*dx+(py-y1)*dy)/l2));return Math.hypot(px-(x1+t*dx),py-(y1+t*dy))}
function updateSeraph(dt){const b=state.boss;state.seraphLaserAngle+=dt*.62;state.seraphTeleportTimer-=dt;state.seraphPulse=Math.max(0,state.seraphPulse-dt);if(state.seraphTeleportTimer<=0){state.seraphTeleportTimer=5.2;state.seraphPulse=.65;const spots=[[.38,.35],[.62,.35],[.38,.57],[.62,.57],[.50,.46]],s=spots[Math.floor(Math.random()*spots.length)];b.x=world.x+world.w*s[0];b.y=world.y+world.h*s[1];state.effects.push({x:b.x,y:b.y,r:28,life:.9,color:'#b77cff'})}if(state.iframeTimer<=0){for(let i=0;i<4;i++){const a=state.seraphLaserAngle+i*Math.PI/2,ex=b.x+Math.cos(a)*520,ey=b.y+Math.sin(a)*520;if(linePointDistance(player.x,player.y,b.x,b.y,ex,ey)<player.r+5){playerHit();break}if(player.drawing){for(const p of player.line){if(linePointDistance(p.x,p.y,b.x,b.y,ex,ey)<5){playerHit();return}}}}}}
function bossAttack(dt){const b=state.boss,d=bossDef();b.angle+=dt*(d.attack==='ricochet'?.25:.45);if(d.attack==='seraph'){updateSeraph(dt);b.attackTimer-=dt;if(b.attackTimer<=0){b.attackTimer=2.2;for(let i=0;i<6;i++)spawnBullet(b.angle+i*Math.PI/3,82,5,{life:7,color:'#b77cff'})}return}b.attackTimer-=dt;if(b.attackTimer>0)return;if(d.attack==='void'){b.attackTimer=remainingCores()<=4?.6:1.05;Math.random()<.6?radialBurst(remainingCores()<=4?20:12):aimedBurst()}else if(d.attack==='ricochet'){b.attackTimer=2.5;for(let i=0;i<5;i++)spawnBullet(b.angle+i*Math.PI*2/5,105,10,{ricochet:true,maxBounces:5,color:'#ff934d'})}if(player.drawing)for(const p of player.line)if(Math.hypot(b.x-p.x,b.y-p.y)<b.r+4){playerHit();break}}
function updateProjectiles(dt){for(let i=state.projectiles.length-1;i>=0;i--){const p=state.projectiles[i];p.life-=dt;if(p.life<=0){state.projectiles.splice(i,1);continue}const nx=p.x+p.vx*dt,ny=p.y+p.vy*dt;if(p.ricochet){let bounced=false;if(nx-p.r<=world.x||nx+p.r>=world.x+world.w){p.vx*=-1;bounced=true}if(ny-p.r<=world.y||ny+p.r>=world.y+world.h){p.vy*=-1;bounced=true}if(isSafeWorld(nx,ny)){p.vx*=-1;p.vy*=-1;bounced=true}p.x+=p.vx*dt;p.y+=p.vy*dt;if(bounced&&++p.bounces>=p.maxBounces){state.projectiles.splice(i,1);continue}}else{p.x=nx;p.y=ny;if(isSafeWorld(p.x,p.y)||p.x<world.x-120||p.x>world.x+world.w+120||p.y<world.y-120||p.y>world.y+world.h+120){state.projectiles.splice(i,1);continue}}if(Math.hypot(p.x-player.x,p.y-player.y)<p.r+player.r){playerHit();state.projectiles.splice(i,1);continue}if(player.drawing){let hit=false;for(const pt of player.line)if(Math.hypot(p.x-pt.x,p.y-pt.y)<p.r+3){hit=true;break}if(hit){playerHit();state.projectiles.splice(i,1)}}}}

function rollCharm(){return DATA.charms[Math.floor(Math.random()*DATA.charms.length)]}
function grantReward(charmId=null){const charm=DATA.charms.find(c=>c.id===charmId)||rollCharm();state.inventory.push(charm.id);save('raidqix.inventory',state.inventory);document.getElementById('rewardName').textContent=charm.name;document.getElementById('rewardDesc').textContent=`${charm.rarity} · ${charm.description}`;setTimeout(()=>openScreen('rewardScreen'),500)}
function winRaid(broadcast=false){if(state.victory||remainingCores()>0)return;state.victory=true;state.gameOver=true;if(state.multiplayer&&state.isHost&&broadcast)sendNet({type:'raid-clear'});grantReward()}
function updateEffects(dt){for(let i=state.effects.length-1;i>=0;i--){const e=state.effects[i];e.life-=dt;e.r+=30*dt;if(e.life<=0)state.effects.splice(i,1)}}
function updateTimers(dt){state.skillCooldown=Math.max(0,state.skillCooldown-dt);state.buffTimer=Math.max(0,state.buffTimer-dt);state.iframeTimer=Math.max(0,state.iframeTimer-dt)}
function q(v,step=2){return Math.round(v/step)*step}

function drawBackground(c){const d=bossDef();c.fillStyle='#05070c';c.fillRect(0,0,LOGICAL_W,LOGICAL_H);const g=c.createRadialGradient(LOGICAL_W*.5,LOGICAL_H*.45,40,LOGICAL_W*.5,LOGICAL_H*.45,520);g.addColorStop(0,d.number===2?'#20140f':d.number===3?'#171021':'#101722');g.addColorStop(1,'#05070c');c.fillStyle=g;c.fillRect(0,0,LOGICAL_W,LOGICAL_H);c.fillStyle='#101722';c.fillRect(world.x,world.y,world.w,world.h);for(let y=0;y<rows;y++)for(let x=0;x<cols;x++)if(grid[y][x]===1){c.fillStyle=d.territory;c.fillRect(world.x+x*GRID,world.y+y*GRID,GRID+1,GRID+1)}c.strokeStyle=d.accent;c.lineWidth=2;c.strokeRect(world.x+.5,world.y+.5,world.w,world.h);c.globalAlpha=.08;c.strokeStyle='#d7e8ff';c.lineWidth=1;for(let x=world.x;x<=world.x+world.w;x+=24){c.beginPath();c.moveTo(x,world.y);c.lineTo(x,world.y+world.h);c.stroke()}for(let y=world.y;y<=world.y+world.h;y+=24){c.beginPath();c.moveTo(world.x,y);c.lineTo(world.x+world.w,y);c.stroke()}c.globalAlpha=1}
function drawRelics(now,c){for(const r of state.relics){if(r.taken)continue;const pulse=1+Math.sin(now*.004+r.phase)*.14;c.save();c.translate(q(r.x),q(r.y));c.scale(pulse,pulse);c.shadowBlur=12;c.shadowColor=r.type.color;c.fillStyle='#080a0f';c.strokeStyle=r.type.color;c.lineWidth=2;c.beginPath();for(let i=0;i<8;i++){const a=Math.PI/8+i*Math.PI/4,rr=i%2?9:13,x=Math.cos(a)*rr,y=Math.sin(a)*rr;i?c.lineTo(x,y):c.moveTo(x,y)}c.closePath();c.fill();c.stroke();c.fillStyle=r.type.color;c.fillRect(-3,-3,6,6);c.restore()}}
function drawVoidBeast(c,b){c.save();c.translate(q(b.x),q(b.y));c.rotate(b.angle*.18);c.shadowBlur=22;c.shadowColor='#ff315c';c.fillStyle='#160c19';c.strokeStyle='#ff315c';c.lineWidth=3;c.beginPath();for(let i=0;i<10;i++){const a=i*Math.PI*2/10,rr=i%2?b.r*.76:b.r*1.12,x=q(Math.cos(a)*rr),y=q(Math.sin(a)*rr);i?c.lineTo(x,y):c.moveTo(x,y)}c.closePath();c.fill();c.stroke();c.rotate(-b.angle*.38);c.strokeStyle='#78233d';c.lineWidth=2;c.strokeRect(-19,-19,38,38);c.fillStyle='#ff416b';c.beginPath();c.arc(0,0,12,0,Math.PI*2);c.fill();c.fillStyle='#ffe8ef';c.fillRect(-3,-7,6,14);c.restore()}
function drawRicochet(c,b){c.save();c.translate(q(b.x),q(b.y));c.rotate(b.angle*.35);c.shadowBlur=22;c.shadowColor='#ff934d';c.fillStyle='#24150e';c.strokeStyle='#ff934d';c.lineWidth=3;c.beginPath();for(let i=0;i<8;i++){const a=Math.PI/8+i*Math.PI/4,rr=i%2?b.r*.82:b.r*1.12,x=q(Math.cos(a)*rr),y=q(Math.sin(a)*rr);i?c.lineTo(x,y):c.moveTo(x,y)}c.closePath();c.fill();c.stroke();c.strokeStyle='#7a3a19';c.lineWidth=4;c.beginPath();c.moveTo(-27,0);c.lineTo(27,0);c.moveTo(0,-27);c.lineTo(0,27);c.stroke();c.fillStyle='#ff934d';c.beginPath();c.arc(0,0,11,0,Math.PI*2);c.fill();c.fillStyle='#fff0dc';c.fillRect(-4,-4,8,8);c.restore()}
function drawSeraph(c,b){c.save();c.translate(q(b.x),q(b.y));c.shadowBlur=25;c.shadowColor='#b77cff';c.rotate(-b.angle*.22);c.strokeStyle='#b77cff';c.lineWidth=3;for(let ring=0;ring<3;ring++){c.beginPath();c.arc(0,0,b.r+ring*9,0,Math.PI*2);c.stroke()}c.rotate(b.angle*.68);c.fillStyle='#120d1b';c.strokeStyle='#dec8ff';c.lineWidth=2;c.beginPath();for(let i=0;i<6;i++){const a=i*Math.PI/3,rr=i%2?29:40,x=q(Math.cos(a)*rr),y=q(Math.sin(a)*rr);i?c.lineTo(x,y):c.moveTo(x,y)}c.closePath();c.fill();c.stroke();c.fillStyle='#b77cff';c.beginPath();c.arc(0,0,10,0,Math.PI*2);c.fill();if(state.seraphPulse>0){c.globalAlpha=state.seraphPulse/.65;c.strokeStyle='#fff';c.lineWidth=2;c.beginPath();c.arc(0,0,55+(1-state.seraphPulse/.65)*55,0,Math.PI*2);c.stroke()}c.globalAlpha=1;c.restore();c.save();c.strokeStyle='rgba(183,124,255,.7)';c.lineWidth=3;for(let i=0;i<4;i++){const a=state.seraphLaserAngle+i*Math.PI/2;c.beginPath();c.moveTo(q(b.x),q(b.y));c.lineTo(q(b.x+Math.cos(a)*520),q(b.y+Math.sin(a)*520));c.stroke()}c.restore()}
function drawBoss(c){if(!state.boss)return;const d=bossDef();if(d.attack==='void')drawVoidBeast(c,state.boss);else if(d.attack==='ricochet')drawRicochet(c,state.boss);else drawSeraph(c,state.boss)}
function drawProjectiles(c){for(const p of state.projectiles){c.save();c.translate(q(p.x),q(p.y));c.shadowBlur=p.ricochet?15:8;c.shadowColor=p.color;c.fillStyle=p.color;if(p.ricochet){c.rotate((p.x+p.y)*.02);c.fillRect(-p.r,-p.r,p.r*2,p.r*2)}else{c.beginPath();c.arc(0,0,p.r,0,Math.PI*2);c.fill()}c.restore()}}
function drawRemotePlayers(c){for(const[id,p]of state.remotePlayers){if(performance.now()-p.updated>1500){state.remotePlayers.delete(id);continue}if(p.drawing&&p.line?.length>1){c.strokeStyle='#ffe066';c.lineWidth=3;c.beginPath();c.moveTo(q(p.line[0].x),q(p.line[0].y));for(let i=1;i<p.line.length;i++)c.lineTo(q(p.line[i].x),q(p.line[i].y));c.stroke()}c.fillStyle='#ffe066';c.beginPath();c.arc(q(p.x),q(p.y),7,0,Math.PI*2);c.fill()}}
function drawPlayer(c){if(player.drawing&&player.line.length>1){c.save();c.strokeStyle='#5deaff';c.lineWidth=3;c.lineCap='round';c.shadowBlur=8;c.shadowColor='#5deaff';c.beginPath();c.moveTo(q(player.line[0].x),q(player.line[0].y));for(let i=1;i<player.line.length;i++)c.lineTo(q(player.line[i].x),q(player.line[i].y));c.stroke();c.restore()}c.save();c.globalAlpha=state.iframeTimer>0?.45:1;c.fillStyle='#fff';c.shadowBlur=12;c.shadowColor='#5deaff';c.beginPath();c.arc(q(player.x),q(player.y),player.r,0,Math.PI*2);c.fill();c.restore()}
function drawEffects(c){for(const e of state.effects){c.save();c.globalAlpha=Math.max(0,e.life);c.strokeStyle=e.color;c.lineWidth=2;c.beginPath();c.arc(q(e.x),q(e.y),e.r,0,Math.PI*2);c.stroke();c.restore()}}
function drawScene(now){drawBackground(sceneCtx);drawRelics(now,sceneCtx);drawProjectiles(sceneCtx);drawBoss(sceneCtx);drawRemotePlayers(sceneCtx);drawPlayer(sceneCtx);drawEffects(sceneCtx);sceneCtx.globalAlpha=.08;sceneCtx.fillStyle='#fff';for(let y=0;y<LOGICAL_H;y+=4)sceneCtx.fillRect(0,y,LOGICAL_W,1);sceneCtx.globalAlpha=1}
function renderPSX(){pixelCtx.setTransform(1,0,0,1,0,0);pixelCtx.imageSmoothingEnabled=false;pixelCtx.clearRect(0,0,PIXEL_W,PIXEL_H);pixelCtx.drawImage(sceneCanvas,0,0,PIXEL_W,PIXEL_H);displayCtx.setTransform(1,0,0,1,0,0);displayCtx.fillStyle='#000';displayCtx.fillRect(0,0,canvas.width,canvas.height);const scale=Math.min(canvas.width/LOGICAL_W,canvas.height/LOGICAL_H),dw=Math.floor(LOGICAL_W*scale),dh=Math.floor(LOGICAL_H*scale),dx=Math.floor((canvas.width-dw)/2),dy=Math.floor((canvas.height-dh)/2);displayCtx.imageSmoothingEnabled=false;if(state.settings.pixelMode)displayCtx.drawImage(pixelCanvas,0,0,PIXEL_W,PIXEL_H,dx,dy,dw,dh);else displayCtx.drawImage(sceneCanvas,0,0,LOGICAL_W,LOGICAL_H,dx,dy,dw,dh)}

function updateHud(){const d=bossDef();document.getElementById('bossName').textContent=state.mode==='raid'?`${d.name} — BOSS ${d.number}`:'NO BOSS';document.getElementById('bossSubtitle').textContent=state.mode==='raid'?d.subtitle:'SELECT RAID';document.getElementById('bossHp').style.width=state.boss?`${Math.max(0,state.boss.hp/state.boss.maxHp*100)}%`:'0%';document.getElementById('bossHp').style.background=d.accent;document.getElementById('area').textContent=Math.floor(state.area);document.getElementById('relics').textContent=state.relicCount;document.getElementById('coreTotal').textContent=state.relics.length||8;document.getElementById('damage').textContent=state.damage;document.getElementById('hp').textContent=`${playerHP}/${playerMaxHP}`;const s=skillDef(),sh=document.getElementById('skillHud');sh.textContent=state.skillCooldown>0?`${s.name} ${state.skillCooldown.toFixed(1)}s`:`${s.name} [E]`;sh.className=state.skillCooldown>0?'skillCooldown':'skillReady';const cds=charmDefs();document.getElementById('charmAHud').textContent=cds[0]?.name||'-';document.getElementById('charmBHud').textContent=cds[1]?.name||'-'}
function openScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id)?.classList.add('active');if(id!=='rewardScreen'&&id!=='settingsScreen'&&id!=='loadoutScreen'&&id!=='lobbyScreen'&&id!=='soloScreen')state.mode='menu';if(id==='loadoutScreen')renderLoadout();if(id==='lobbyScreen')refreshSteam()}
document.querySelectorAll('[data-open]').forEach(el=>el.onclick=()=>openScreen(el.dataset.open));
function renderBossCards(targetId){const target=document.getElementById(targetId);target.innerHTML='';for(const b of DATA.bosses){const el=document.createElement('button');el.className='card'+(state.bossId===b.id?' selected':'');el.innerHTML=`<strong>BOSS ${b.number} · ${b.name}</strong><small>${b.description}</small>`;el.onclick=()=>{state.bossId=b.id;renderBossCards('soloBossGrid');renderBossCards('lobbyBossGrid')};target.appendChild(el)}}
renderBossCards('soloBossGrid');renderBossCards('lobbyBossGrid');document.getElementById('soloStart').onclick=()=>startRaid(false,false);
function startRaid(multiplayer,broadcast){state.multiplayer=multiplayer;state.mode='raid';document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));resetGame();if(multiplayer&&broadcast)sendNet({type:'raid-start',bossId:state.bossId,relics:state.relics,grid:cloneGrid()})}
function renderLoadout(){const sg=document.getElementById('skillGrid');sg.innerHTML='';for(const s of DATA.skills){const el=document.createElement('button');el.className='card'+(state.equippedSkill===s.id?' selected':'');el.innerHTML=`<strong>${s.name}</strong><small>${s.description}<br>CD ${s.cooldown}s</small>`;el.onclick=()=>{state.equippedSkill=s.id;save('raidqix.skill',s.id);renderLoadout()};sg.appendChild(el)}const cg=document.getElementById('charmGrid');cg.innerHTML='';for(const c of DATA.charms.filter(c=>state.inventory.includes(c.id))){const el=document.createElement('button');el.className='card'+(state.equippedCharms.includes(c.id)?' selected':'');el.innerHTML=`<strong>${c.name}</strong><small>${c.rarity} · ${c.description}</small>`;el.onclick=()=>toggleCharm(c.id);cg.appendChild(el)}document.getElementById('inventoryText').textContent=`OWNED CHARMS: ${state.inventory.length} · DUPLICATES ARE KEPT FOR FUTURE SYSTEMS`}
function toggleCharm(id){const a=[...state.equippedCharms],i=a.indexOf(id);if(i>=0)a.splice(i,1);else if(a.length<2)a.push(id);else a[1]=id;state.equippedCharms=a;save('raidqix.charms',a);renderLoadout();updateHud()}
const volume=document.getElementById('volume');volume.value=state.settings.volume;document.getElementById('screenShake').checked=state.settings.screenShake;document.getElementById('pixelMode').checked=state.settings.pixelMode;document.getElementById('volLabel').textContent=volume.value;volume.oninput=()=>{state.settings.volume=+volume.value;document.getElementById('volLabel').textContent=volume.value;save('raidqix.settings',state.settings)};document.getElementById('screenShake').onchange=e=>{state.settings.screenShake=e.target.checked;save('raidqix.settings',state.settings)};document.getElementById('pixelMode').onchange=e=>{state.settings.pixelMode=e.target.checked;save('raidqix.settings',state.settings)};document.getElementById('rewardContinue').onclick=()=>{renderLoadout();openScreen('titleScreen')};
async function refreshSteam(){if(!window.raidAPI){document.getElementById('steamStatus').textContent='Electron bridge unavailable';return}applySteamState(await window.raidAPI.getSteamState())}
function applySteamState(s){state.members=s.members||[];state.localSteamId=s.localId||state.localSteamId;document.getElementById('steamStatus').textContent=s.enabled?`STEAM ONLINE${s.lobbyId?' · '+s.lobbyId:''}`:'OFFLINE FALLBACK';renderMembers()}
function renderMembers(){const el=document.getElementById('members');el.innerHTML=state.members.length?state.members.map(m=>`<div class="member">${m.host?'HOST · ':''}${m.name}</div>`).join(''):'<div class="muted">No lobby members</div>'}
function sendNet(payload){return window.raidAPI?.send(payload).catch(()=>false)}
document.getElementById('createLobby').onclick=async()=>{const s=await window.raidAPI.createLobby({maxMembers:4});state.isHost=true;applySteamState(s)};
document.getElementById('joinLobby').onclick=async()=>{const id=document.getElementById('lobbyIdInput').value.trim();if(!id)return;const s=await window.raidAPI.joinLobby(id);state.isHost=false;applySteamState(s)};
document.getElementById('leaveLobby').onclick=async()=>{await window.raidAPI.leaveLobby();state.members=[];state.isHost=false;state.remotePlayers.clear();renderMembers();refreshSteam()};document.getElementById('lobbyStart').onclick=()=>{if(state.isHost)startRaid(true,true)};
function onNetMessage(m){if(!m||m.senderId===state.localSteamId)return;if(m.type==='lobby-state'){applySteamState(m);return}if(m.type==='raid-start'&&!state.isHost){state.bossId=m.bossId;startRaid(true,false);if(m.relics)state.relics=m.relics;if(m.grid)setGrid(m.grid);return}if(m.type==='player-state'&&state.mode==='raid'){state.remotePlayers.set(m.senderId,{x:m.x,y:m.y,drawing:m.drawing,line:m.line||[],hp:m.hp,maxHp:m.maxHp,name:m.name,updated:performance.now()});return}if(m.type==='world-state'&&state.multiplayer&&!state.isHost&&state.mode==='raid'){if(m.boss&&state.boss)Object.assign(state.boss,m.boss);if(Array.isArray(m.projectiles))state.projectiles=m.projectiles;if(Number.isFinite(m.seraphLaserAngle))state.seraphLaserAngle=m.seraphLaserAngle;return}if(m.type==='core-destroyed'&&state.isHost&&state.mode==='raid'&&state.boss){state.boss.hp=Math.max(Math.max(1,Number(m.remaining)||1),state.boss.hp-Math.max(0,Number(m.amount)||0));if(Number(m.remaining)===0){state.boss.hp=0;winRaid(true)}return}if(m.type==='capture-state'&&state.isHost&&state.mode==='raid'){mergeGrid(m.grid);sendNet({type:'grid-state',grid:cloneGrid()});return}if(m.type==='grid-state'&&!state.isHost&&state.mode==='raid'){setGrid(m.grid);return}if(m.type==='raid-clear'&&!state.isHost&&state.mode==='raid'){state.relics.forEach(r=>r.taken=true);winRaid(false)}}
window.raidAPI?.onMessage(onNetMessage);
function networkTick(dt){if(!state.multiplayer||state.mode!=='raid')return;state.netPlayerTimer-=dt;state.netWorldTimer-=dt;if(state.netPlayerTimer<=0){state.netPlayerTimer=.08;const line=player.drawing?player.line.filter((_,i)=>i%Math.max(1,Math.ceil(player.line.length/60))===0):[];sendNet({type:'player-state',x:player.x,y:player.y,drawing:player.drawing,line,hp:playerHP,maxHp:playerMaxHP,name:state.members.find(m=>m.id===state.localSteamId)?.name||'Player'})}if(state.isHost&&state.netWorldTimer<=0){state.netWorldTimer=.10;sendNet({type:'world-state',boss:state.boss,projectiles:state.projectiles,seraphLaserAngle:state.seraphLaserAngle})}}
let last=performance.now();function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(state.mode==='raid'&&!state.gameOver){movePlayer(dt);if(!state.multiplayer||state.isHost)bossAttack(dt);updateProjectiles(dt);updateEffects(dt);updateTimers(dt);networkTick(dt)}drawScene(now);renderPSX();updateHud();requestAnimationFrame(loop)}
buildGrid();resizeDisplay();resetBoss();resetPlayer();refreshSteam();requestAnimationFrame(loop);
