// RAID QIX v0.9.2
// Persistent rotating lasers, paced random scheduler, and expanded gimmick library.

Object.assign(state,{
  sweepLasers:[],
  sweepLaserSeq:0,
  randomGimmickTimer:1.25,
  randomLastCategory:null,
  randomAreaStreak:0,
  orbitAngle:0,
  bossDashTimer:3.8,
  bossDashTime:0,
  bossDashVx:0,
  bossDashVy:0
});

function spawnSweepLaser(opts={}){
  const laser={id:++state.sweepLaserSeq,x:opts.x??state.boss.x,y:opts.y??state.boss.y,angle:opts.angle??Math.random()*Math.PI*2,angularSpeed:opts.angularSpeed??.18,count:opts.count??2,length:opts.length??1400,width:opts.width??28,warning:opts.warning??1.0,duration:opts.duration??3.8,color:opts.color||bossDef().accent||'#b77cff',followBoss:opts.followBoss!==false,active:false};
  state.sweepLasers.push(laser);return laser;
}
function updateSweepLasers(dt,advance=true){for(let i=state.sweepLasers.length-1;i>=0;i--){const l=state.sweepLasers[i];if(l.followBoss&&state.boss){l.x=state.boss.x;l.y=state.boss.y}if(l.warning>0){if(advance)l.warning-=dt;if(l.warning<=0)l.active=true}else if(l.active){if(advance){l.angle+=l.angularSpeed*dt;l.duration-=dt}if(state.iframeTimer<=0){for(let arm=0;arm<l.count;arm++){const a=l.angle+arm*Math.PI*2/l.count,ex=l.x+Math.cos(a)*l.length,ey=l.y+Math.sin(a)*l.length;if(pointSegmentDistance(player.x,player.y,l.x,l.y,ex,ey)<=l.width*.5+player.r){playerHit();break}}}}if(l.duration<=0&&advance)state.sweepLasers.splice(i,1)}}
function drawSweepLasers(c){for(const l of state.sweepLasers){for(let arm=0;arm<l.count;arm++){const a=l.angle+arm*Math.PI*2/l.count,ex=l.x+Math.cos(a)*l.length,ey=l.y+Math.sin(a)*l.length;c.save();if(l.warning>0){c.globalAlpha=.38;c.strokeStyle=l.color;c.lineWidth=2;c.setLineDash([10,9])}else{c.globalAlpha=.9;c.strokeStyle='#fff';c.shadowBlur=22;c.shadowColor=l.color;c.lineWidth=Math.max(6,l.width*.36);c.setLineDash([])}c.beginPath();c.moveTo(q(l.x),q(l.y));c.lineTo(q(ex),q(ey));c.stroke();if(l.warning<=0){c.globalAlpha=.55;c.strokeStyle=l.color;c.lineWidth=l.width;c.beginPath();c.moveTo(q(l.x),q(l.y));c.lineTo(q(ex),q(ey));c.stroke()}c.restore()}}}
attackRotatingLasers=function(cfg={}){spawnSweepLaser({count:cfg.count??(Math.random()<.6?2:4),angularSpeed:cfg.angularSpeed??v08Rand(.09,.20),width:cfg.width??v08Rand(24,36),warning:cfg.warning??.9,duration:cfg.duration??v08Rand(3.0,4.8),color:cfg.color||bossDef().accent})};
ATTACK_LIBRARY.rotatingLasers={weight:13,run:attackRotatingLasers};
ATTACK_LIBRARY.rotatingWall={weight:10,run:cfg=>spawnSweepLaser({count:cfg.count??3,angularSpeed:cfg.angularSpeed??v08Rand(.12,.24),width:cfg.width??30,warning:cfg.warning??.85,duration:cfg.duration??3.3,color:cfg.color||bossDef().accent})};

function attackBrokenRing(cfg={}){const count=cfg.count??16,safeEvery=cfg.safeEvery??4,base=state.boss.angle||0;for(let i=0;i<count;i++){if(i%safeEvery===0)continue;const a=base+i*Math.PI*2/count;spawnBullet(a,cfg.speed??88,cfg.size??5,{life:12,color:cfg.color||'#ff9e61'})}}
function attackQuadrantSafe(cfg={}){const safe=Math.floor(Math.random()*4);for(let i=0;i<4;i++){if(i===safe||i===(safe+2)%4)continue;spawnConeTelegraph(state.boss.x,state.boss.y,i*Math.PI/2+Math.PI/4,cfg.range??520,Math.PI/4*.92,{warning:cfg.warning??1.55,color:cfg.color||'#ff775b'})}}
function attackPredictionFeint(cfg={}){const p=predictiveAimPoint(cfg.lead??.75);spawnTelegraphCircle(p.x,p.y,cfg.radius??72,{warning:cfg.warning??1.45,color:cfg.color||'#ff4f76'});const ox=player.x-(p.x-player.x)*.8,oy=player.y-(p.y-player.y)*.8;spawnTelegraphCircle(ox,oy,cfg.radius??60,{warning:(cfg.warning??1.45)+.42,color:cfg.color||'#ff94ab'})}
function attackClockSpots(cfg={}){const count=cfg.count??8,start=Math.floor(Math.random()*2),radius=cfg.orbitRadius??210;for(let i=0;i<count;i++){if(i%2===start)continue;const a=i*Math.PI*2/count;spawnTelegraphCircle(state.boss.x+Math.cos(a)*radius,state.boss.y+Math.sin(a)*radius,cfg.radius??64,{warning:cfg.warning??1.65,color:cfg.color||'#7ca8ff'})}}
function attackFootsteps(cfg={}){const baseX=player.x,baseY=player.y,dx=player.dx||1,dy=player.dy||0;for(let i=0;i<(cfg.count??5);i++)spawnTelegraphCircle(baseX+dx*i*(cfg.spacing??65),baseY+dy*i*(cfg.spacing??65),cfg.radius??48,{warning:(cfg.warning??1.1)+i*(cfg.step??.22),color:cfg.color||'#dc78ff'})}
function attackInOutCombo(cfg={}){spawnTelegraphCircle(state.boss.x,state.boss.y,cfg.innerRadius??125,{warning:1.15,color:cfg.color||'#ff995c'});spawnDonutTelegraph(state.boss.x,state.boss.y,75,250,{warning:1.75,color:cfg.color||'#ffca6b'});spawnTelegraphCircle(state.boss.x,state.boss.y,cfg.innerRadius??125,{warning:2.35,color:cfg.color||'#ff995c'})}
function attackDoubleSpiral(cfg={}){const count=cfg.count??8,base=state.randomPhase||0;for(let i=0;i<count;i++){const a=base+i*.22;spawnBullet(a,cfg.speed??96,5,{life:12,color:cfg.color||'#c785ff'});spawnBullet(a+Math.PI,cfg.speed??96,5,{life:12,color:cfg.color||'#73b5ff'})}state.randomPhase=(state.randomPhase||0)+.62}
function attackStripeSwap(cfg={}){const horizontal=Math.random()<.5,lanes=cfg.lanes??10,parity=Math.floor(Math.random()*2);if(horizontal){const h=world.h/lanes;for(let i=0;i<lanes;i++){if(i%2!==parity)continue;const y=world.y+h*(i+.5);spawnLineTelegraph(world.x,y,world.x+world.w,y,h*.65,{warning:cfg.warning??1.45,color:cfg.color||'#58b6ff'})}}else{const w=world.w/lanes;for(let i=0;i<lanes;i++){if(i%2!==parity)continue;const x=world.x+w*(i+.5);spawnLineTelegraph(x,world.y,x,world.y+world.h,w*.65,{warning:cfg.warning??1.45,color:cfg.color||'#58b6ff'})}}}
function attackBossDash(cfg={}){state.bossDashTime=cfg.duration??1.25;const a=Math.atan2(player.y-state.boss.y,player.x-state.boss.x)+v08Rand(-.45,.45),speed=cfg.speed??48;state.bossDashVx=Math.cos(a)*speed;state.bossDashVy=Math.sin(a)*speed}
function attackOrbitBurst(cfg={}){const count=cfg.count??10,radius=cfg.radius??95;for(let i=0;i<count;i++){const a=i*Math.PI*2/count,px=state.boss.x+Math.cos(a)*radius,py=state.boss.y+Math.sin(a)*radius,outward=a+v08Rand(-.22,.22);state.projectiles.push({x:px,y:py,vx:Math.cos(outward)*(cfg.speed??74),vy:Math.sin(outward)*(cfg.speed??74),r:cfg.size??5,life:12,color:cfg.color||'#89e4ff'})}}
Object.assign(ATTACK_LIBRARY,{brokenRing:{weight:8,category:'bullet',run:attackBrokenRing},quadrantSafe:{weight:8,category:'area',run:attackQuadrantSafe},predictionFeint:{weight:8,category:'area',run:attackPredictionFeint},clockSpots:{weight:8,category:'area',run:attackClockSpots},footsteps:{weight:8,category:'area',run:attackFootsteps},inOutCombo:{weight:7,category:'area',run:attackInOutCombo},doubleSpiral:{weight:8,category:'bullet',run:attackDoubleSpiral},stripeSwap:{weight:9,category:'area',run:attackStripeSwap},bossDash:{weight:5,category:'movement',run:attackBossDash},orbitBurst:{weight:8,category:'bullet',run:attackOrbitBurst}});
const AREA_KEYS=new Set(['predictiveLine','cone','donut','pointBlank','chasingAoE','checkerboard','crossLines','sequentialLines','curtain','safeLane','expandingRings','collapsingRings','triplePrediction','pizzaSlices','alternatingCross','edgeIn','meteorSpread','baitAndSpread','rotatingWall','quadrantSafe','predictionFeint','clockSpots','footsteps','inOutCombo','stripeSwap','rotatingLasers']);
const BULLET_KEYS=new Set(['radial','aimed','predictiveShot','sineCurtain','spiral','triangleBreak','brokenRing','doubleSpiral','orbitBurst']);
function attackCategory(key){if(ATTACK_LIBRARY[key]?.category)return ATTACK_LIBRARY[key].category;if(AREA_KEYS.has(key))return'area';if(BULLET_KEYS.has(key))return'bullet';return'utility'}
function v092AttackInterval(floor,category){const progression=Math.min(.52,(floor-1)*.014),baseMin=1.15-progression,baseMax=1.75-progression*.95;let v=v08Rand(Math.max(.64,baseMin),Math.max(.92,baseMax));if(category==='area')v+=.18;return v}
function v092ChooseAttack(){let pool=state.v08RandomPattern.length?state.v08RandomPattern:[];if(!pool.length){const floor=state.randomRun.floor||1;state.v08RandomPattern=v08RandomBossPattern(floor);pool=state.v08RandomPattern}if(state.randomAreaStreak>=2){const alternatives=pool.filter(x=>attackCategory(x.key)!=='area');if(alternatives.length)pool=alternatives}else if(state.randomLastCategory==='area'){const alternatives=pool.filter(x=>attackCategory(x.key)!=='area');if(alternatives.length&&Math.random()<.72)pool=alternatives}return v08Pick(pool)}
function v092RunRandomBoss(dt){const cfg=state.randomRun.config,b=state.boss;if(!cfg||!b)return;b.angle=(b.angle||0)+dt*(state.bossSpinSpeed||.07);b.x+=state.v091RandomVx*dt;b.y+=state.v091RandomVy*dt;const pad=155;if(b.x<world.x+pad){b.x=world.x+pad;state.v091RandomVx=Math.abs(state.v091RandomVx)}if(b.x>world.x+world.w-pad){b.x=world.x+world.w-pad;state.v091RandomVx=-Math.abs(state.v091RandomVx)}if(b.y<world.y+pad){b.y=world.y+pad;state.v091RandomVy=Math.abs(state.v091RandomVy)}if(b.y>world.y+world.h-pad){b.y=world.y+world.h-pad;state.v091RandomVy=-Math.abs(state.v091RandomVy)}if(state.bossDashTime>0){state.bossDashTime-=dt;b.x+=state.bossDashVx*dt;b.y+=state.bossDashVy*dt}if(cfg.gravity&&state.iframeTimer<=0){const dx=b.x-player.x,dy=b.y-player.y,dist=Math.max(80,Math.hypot(dx,dy));if(dist<330){const pull=Math.min(42,state.randomGravityStrength||26);player.x+=dx/dist*pull*dt;player.y+=dy/dist*pull*dt}}state.randomGimmickTimer-=dt;if(state.randomGimmickTimer<=0){const entry=v092ChooseAttack(),category=attackCategory(entry.key);ATTACK_LIBRARY[entry.key]?.run(entry.cfg);state.randomLastCategory=category;state.randomAreaStreak=category==='area'?state.randomAreaStreak+1:0;state.randomGimmickTimer=v092AttackInterval(state.randomRun.floor||1,category)}updateTelegraphs(dt,true);updateExtraTelegraphs(dt,true);updateSweepLasers(dt,true)}
v091RandomBossUpdate=v092RunRandomBoss;
const _v091BossAttack092=bossAttack;bossAttack=function(dt){_v091BossAttack092(dt);if(!state.randomRun?.active)updateSweepLasers(dt,true)};
const _v091SetupRandomFloor092=setupRandomBossForFloor;setupRandomBossForFloor=function(floor,first=false){_v091SetupRandomFloor092(floor,first);const keys=Object.keys(ATTACK_LIBRARY),desired=Math.min(9,4+Math.floor(floor/3));state.v08RandomPattern=[];while(state.v08RandomPattern.length<desired&&keys.length){const key=v08Pick(keys);if(state.v08RandomPattern.some(x=>x.key===key))continue;state.v08RandomPattern.push({key,cfg:randomizeAttackConfig(key,floor)})}v091SetupRandomMotion();state.v091RandomMoveSpeed=v08Rand(6,14);const a=Math.random()*Math.PI*2;state.v091RandomVx=Math.cos(a)*state.v091RandomMoveSpeed;state.v091RandomVy=Math.sin(a)*state.v091RandomMoveSpeed;if(Math.random()<.58&&!state.v08RandomPattern.some(x=>x.key==='rotatingLasers'))state.v08RandomPattern.push({key:'rotatingLasers',cfg:randomizeAttackConfig('rotatingLasers',floor)});state.randomGimmickTimer=v08Rand(1.05,1.45);state.randomAreaStreak=0;state.randomLastCategory=null;state.sweepLasers=[];state.bossDashTime=0};
const _v091ResetBoss092=resetBoss;resetBoss=function(){_v091ResetBoss092();state.sweepLasers=[];state.randomGimmickTimer=1.2;state.randomAreaStreak=0;state.randomLastCategory=null;state.bossDashTime=0};
const _v091DrawScene092=drawScene;drawScene=function(now){_v091DrawScene092(now);drawSweepLasers(sceneCtx)};
