// RAID QIX v0.9 stability, boss motion, random mechanics, rewards and inventory upgrade.

Object.assign(state,{bossSpinSpeed:.09,bossMoveSpeed:0,bossMoveAngle:0,bossMoveEnabled:false,v09ImpactFx:[],v09RewardGranted:false,selectedInventoryCharm:null,randomCompleted:0});
const RARITY_ORDER=['COMMON','UNCOMMON','RARE','EPIC'];
const RARITY_COLOR={COMMON:'#a7b0bd',UNCOMMON:'#4bdf7a',RARE:'#4aa4ff',EPIC:'#c06cff'};
function v09CharmById(id){return DATA.charms.find(c=>c.id===id)}
function v09InventoryCounts(){const m=new Map();for(const id of state.inventory)m.set(id,(m.get(id)||0)+1);return m}

updateTelegraphs=function(dt,advance=true){for(let i=state.telegraphs.length-1;i>=0;i--){const t=state.telegraphs[i],prev=t.warning;if(advance)t.warning-=dt;if(prev>0&&t.warning<=0){t.justImpacted=true;t.active=Math.max(t.active??.18,.18);state.v09ImpactFx.push({x:t.x,y:t.y,r:t.r,life:.28,color:t.color||'#ff4fd8'})}if(t.warning<=0){if(!t.hitResolved){t.hitResolved=true;if(state.iframeTimer<=0&&Math.hypot(player.x-t.x,player.y-t.y)<=t.r+player.r)playerHit()}if(advance)t.active-=dt;if(t.active<=0&&advance)state.telegraphs.splice(i,1)}}};

attackCurtain=function(cfg={}){const vertical=Math.random()<.5,lanes=Math.max(6,cfg.lanes??10),warning=cfg.warning??1.55;if(vertical){const laneW=world.w/lanes,parity=Math.random()<.5?0:1;for(let i=0;i<lanes;i++){if(i%2!==parity)continue;const x=world.x+laneW*(i+.5);spawnLineTelegraph(x,world.y,x,world.y+world.h,laneW*.72,{warning,color:cfg.color||'#87d7ff'})}}else{const laneH=world.h/lanes,parity=Math.random()<.5?0:1;for(let i=0;i<lanes;i++){if(i%2!==parity)continue;const y=world.y+laneH*(i+.5);spawnLineTelegraph(world.x,y,world.x+world.w,y,laneH*.72,{warning,color:cfg.color||'#87d7ff'})}}};

function attackExpandingRings(cfg={}){const count=cfg.count??3;for(let i=0;i<count;i++)spawnDonutTelegraph(state.boss.x,state.boss.y,55+i*68,105+i*68,{warning:(cfg.warning??1.25)+i*.28,color:cfg.color||'#ffb757'})}
function attackCollapsingRings(cfg={}){const count=cfg.count??3;for(let i=0;i<count;i++){const j=count-1-i;spawnDonutTelegraph(state.boss.x,state.boss.y,55+j*68,105+j*68,{warning:(cfg.warning??1.25)+i*.28,color:cfg.color||'#f58cff'})}}
function attackTriplePrediction(cfg={}){for(let i=0;i<3;i++){const p=predictiveAimPoint((cfg.lead??.35)+i*.28);spawnTelegraphCircle(p.x,p.y,(cfg.radius??58)+i*7,{warning:(cfg.warning??1.25)+i*.18,color:cfg.color||'#ff5a6f'})}}
function attackPizzaSlices(cfg={}){const slices=cfg.slices??8,safe=Math.floor(Math.random()*slices);for(let i=0;i<slices;i++){if(i===safe||i===(safe+1)%slices)continue;spawnConeTelegraph(state.boss.x,state.boss.y,i*Math.PI*2/slices,390,Math.PI/slices*.42,{warning:cfg.warning??1.7,color:cfg.color||'#ff944f'})}}
function attackAlternatingCross(cfg={}){const offset=Math.random()<.5?0:Math.PI/4;for(let i=0;i<4;i++){const a=offset+i*Math.PI/2;spawnLineTelegraph(state.boss.x,state.boss.y,state.boss.x+Math.cos(a)*1200,state.boss.y+Math.sin(a)*1200,cfg.width??42,{warning:cfg.warning??1.45,color:cfg.color||'#ff668d'})}}
function attackEdgeIn(cfg={}){const lanes=cfg.lanes??8,safe=Math.floor(Math.random()*lanes),laneW=world.w/lanes;for(let i=0;i<lanes;i++){if(i===safe)continue;const x=world.x+laneW*(i+.5);spawnLineTelegraph(x,world.y,x,world.y+world.h,laneW*.58,{warning:cfg.warning??1.75,color:cfg.color||'#79b7ff'})}}
function attackMeteorSpread(cfg={}){const count=cfg.count??6;for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,dist=Math.random()*220;spawnTelegraphCircle(player.x+Math.cos(a)*dist,player.y+Math.sin(a)*dist,cfg.radius??54,{warning:(cfg.warning??1.35)+Math.random()*.55,color:cfg.color||'#ff6a4a'})}}
function attackBaitAndSpread(cfg={}){spawnChasingCircle(player.x,player.y,cfg.radius??68,{warning:2.15,follow:1.05,color:cfg.color||'#e45cff'});for(let i=0;i<3;i++)spawnRandomTelegraph(55,1.8+i*.18,cfg.color||'#e45cff')}
function attackRotatingWall(cfg={}){const count=cfg.count??3,base=state.randomLaserAngle||0;for(let i=0;i<count;i++){const a=base+i*Math.PI/count;spawnLineTelegraph(state.boss.x,state.boss.y,state.boss.x+Math.cos(a)*1300,state.boss.y+Math.sin(a)*1300,cfg.width??30,{warning:cfg.warning??.75,active:.18,color:cfg.color||'#b77cff'})}}
Object.assign(ATTACK_LIBRARY,{expandingRings:{weight:6,run:attackExpandingRings},collapsingRings:{weight:6,run:attackCollapsingRings},triplePrediction:{weight:8,run:attackTriplePrediction},pizzaSlices:{weight:7,run:attackPizzaSlices},alternatingCross:{weight:7,run:attackAlternatingCross},edgeIn:{weight:7,run:attackEdgeIn},meteorSpread:{weight:8,run:attackMeteorSpread},baitAndSpread:{weight:7,run:attackBaitAndSpread},rotatingWall:{weight:8,run:attackRotatingWall}});ATTACK_LIBRARY.rotatingLasers.weight=10;

const _v08SetupRandomBossForFloor=typeof setupRandomBossForFloor==='function'?setupRandomBossForFloor:null;
function v09SetupBossMotion(randomized=true){state.bossSpinSpeed=randomized?v08Rand(.045,.11):.075;state.bossMoveSpeed=randomized?v08Rand(5,16):8;state.bossMoveAngle=Math.random()*Math.PI*2;state.bossMoveEnabled=true;if(state.boss){state.boss.v09vx=Math.cos(state.bossMoveAngle)*state.bossMoveSpeed;state.boss.v09vy=Math.sin(state.bossMoveAngle)*state.bossMoveSpeed}}
if(_v08SetupRandomBossForFloor){setupRandomBossForFloor=function(floor,first=false){_v08SetupRandomBossForFloor(floor,first);if(state.randomRun?.config){state.randomRun.config.drift=true;state.randomRun.config.driftSpeed=v08Rand(5,15);state.randomRun.config.laser=Math.random()<.62;state.randomRun.config.laserSpeed=v08Rand(.045,.12)}state.v08RandomPattern=v08RandomBossPattern(floor);v09SetupBossMotion(true);state.randomCompleted=Math.max(0,floor-1);state.v09RewardGranted=false}}
const _v08ResetBoss9=resetBoss;resetBoss=function(){_v08ResetBoss9();v09SetupBossMotion(true)};
function v09CommonBossMotion(dt){const b=state.boss;if(!b)return;b.angle=(b.angle||0)+dt*state.bossSpinSpeed;if(state.randomRun?.active)return;if(state.bossMoveEnabled){b.v09vx=b.v09vx??Math.cos(state.bossMoveAngle)*state.bossMoveSpeed;b.v09vy=b.v09vy??Math.sin(state.bossMoveAngle)*state.bossMoveSpeed;b.x+=b.v09vx*dt;b.y+=b.v09vy*dt;const pad=150;if(b.x<world.x+pad){b.x=world.x+pad;b.v09vx=Math.abs(b.v09vx)}if(b.x>world.x+world.w-pad){b.x=world.x+world.w-pad;b.v09vx=-Math.abs(b.v09vx)}if(b.y<world.y+pad){b.y=world.y+pad;b.v09vy=Math.abs(b.v09vy)}if(b.y>world.y+world.h-pad){b.y=world.y+world.h-pad;b.v09vy=-Math.abs(b.v09vy)}}}
const _v08BossAttack9=bossAttack;bossAttack=function(dt){const before=state.boss?.angle||0;_v08BossAttack9(dt);if(state.boss)state.boss.angle=before+dt*state.bossSpinSpeed;v09CommonBossMotion(dt)};
const _v08RandomBossUpdate9=typeof randomBossUpdate==='function'?randomBossUpdate:null;if(_v08RandomBossUpdate9){randomBossUpdate=function(dt){_v08RandomBossUpdate9(dt);const cfg=state.randomRun.config,b=state.boss;if(cfg?.laser&&b&&v08Timer('randomVisibleLaser',dt,1.25)){attackRotatingLasers({count:Math.random()<.5?2:4,width:v08Rand(18,30),warning:.65,active:.15,color:bossDef().accent})}updateExtraTelegraphs(dt,true)}}

function v09RollCharm(){const r=Math.random(),rarity=r<.52?'COMMON':r<.80?'UNCOMMON':r<.96?'RARE':'EPIC',pool=DATA.charms.filter(c=>c.rarity===rarity);return (pool.length?pool:DATA.charms)[Math.floor(Math.random()*(pool.length||DATA.charms.length))]}
function v09GrantRandomRunRewards(count){const rewards=[];for(let i=0;i<count;i++){const c=v09RollCharm();state.inventory.push(c.id);rewards.push(c)}save('raidqix.inventory',state.inventory);return rewards}
const _v07PlayerHit9=playerHit;playerHit=function(){const wasRandom=!!state.randomRun?.active,before=playerHP;_v07PlayerHit9();if(wasRandom&&before>0&&playerHP<=0&&!state.v09RewardGranted){state.v09RewardGranted=true;const defeated=Math.max(0,(state.randomRun?.floor||1)-1),rewards=v09GrantRandomRunRewards(defeated);state.randomCompleted=defeated;document.getElementById('rewardName').textContent=`RANDOM RAID · ${defeated} BOSSES`;document.getElementById('rewardDesc').textContent=`獲得 ${rewards.length}個: ${rewards.length?rewards.map(c=>c.name).slice(0,6).join(' / ')+(rewards.length>6?` +${rewards.length-6}`:''):'NO REWARD'}`;setTimeout(()=>openScreen('rewardScreen'),180)}};

function v09RenderItemDetail(charm){const el=document.getElementById('itemDetail');if(!el)return;if(!charm){el.className='card';el.innerHTML='<strong>SELECT AN ITEM</strong><small>アイテムをクリックすると詳細を表示します。</small>';return}const count=v09InventoryCounts().get(charm.id)||0;el.className=`card rarity-${charm.rarity}`;el.innerHTML=`<strong>${charm.name}</strong><small style="color:${RARITY_COLOR[charm.rarity]}">${charm.rarity}</small><div style="margin-top:18px;line-height:1.65">${charm.description}</div><div class="muted" style="margin-top:18px">OWNED × ${count}<br>ID: ${charm.id}</div><button id="detailEquip" class="btn" style="margin-top:18px;width:100%"><strong>${state.equippedCharms.includes(charm.id)?'UNEQUIP':'EQUIP'}</strong><small>チャームスロットへ反映</small></button>`;document.getElementById('detailEquip').onclick=()=>{toggleCharm(charm.id);v09RenderInventory();v09RenderItemDetail(charm)}}
function v09RenderInventory(){const grid=document.getElementById('inventoryGrid');if(!grid)return;const counts=v09InventoryCounts();grid.innerHTML='';const unique=[...counts.keys()].map(v09CharmById).filter(Boolean).sort((a,b)=>RARITY_ORDER.indexOf(b.rarity)-RARITY_ORDER.indexOf(a.rarity)||a.name.localeCompare(b.name));for(const c of unique){const el=document.createElement('button');el.className=`card inventoryItem rarity-${c.rarity}${state.selectedInventoryCharm===c.id?' selected':''}`;el.innerHTML=`<span class="inventoryCount">×${counts.get(c.id)}</span><strong>${c.name}</strong><small>${c.rarity}</small>`;el.onclick=()=>{state.selectedInventoryCharm=c.id;v09RenderInventory();v09RenderItemDetail(c)};grid.appendChild(el)}document.getElementById('inventoryText').textContent=`OWNED ITEMS: ${state.inventory.length} · UNIQUE: ${unique.length}`;const selected=v09CharmById(state.selectedInventoryCharm);if(selected)v09RenderItemDetail(selected)}
const _v08RenderLoadout9=renderLoadout;renderLoadout=function(){_v08RenderLoadout9();v09RenderInventory();const counts=v09InventoryCounts(),sel=document.getElementById('fusionRarity'),status=document.getElementById('fusionStatus');if(sel&&status){const rarity=sel.value,total=[...counts.entries()].reduce((n,[id,c])=>n+(v09CharmById(id)?.rarity===rarity?c:0),0);status.textContent=`${rarity}: ${total}個所持 / 3個で合成可能`}};
function v09FuseRarity(rarity){const idx=RARITY_ORDER.indexOf(rarity);if(idx<0||idx>=RARITY_ORDER.length-1)return{ok:false,msg:'このレアリティは合成できません'};const candidates=[];state.inventory.forEach((id,i)=>{if(v09CharmById(id)?.rarity===rarity)candidates.push({id,i})});if(candidates.length<3)return{ok:false,msg:`${rarity}が3個必要です`};for(const i of candidates.slice(0,3).map(x=>x.i).sort((a,b)=>b-a))state.inventory.splice(i,1);const next=RARITY_ORDER[idx+1],pool=DATA.charms.filter(c=>c.rarity===next);if(!pool.length)return{ok:false,msg:`${next}のアイテムがまだありません`};const result=pool[Math.floor(Math.random()*pool.length)];state.inventory.push(result.id);save('raidqix.inventory',state.inventory);return{ok:true,msg:`${rarity} ×3 → ${result.name} [${next}]`,item:result}}
document.getElementById('fusionRarity')?.addEventListener('change',()=>renderLoadout());document.getElementById('fusionButton')?.addEventListener('click',()=>{const rarity=document.getElementById('fusionRarity').value,result=v09FuseRarity(rarity);document.getElementById('fusionStatus').textContent=result.msg;if(result.item){state.selectedInventoryCharm=result.item.id;renderLoadout();v09RenderItemDetail(result.item)}});
const _v08DrawScene9=drawScene;drawScene=function(now){_v08DrawScene9(now);for(let i=state.v09ImpactFx.length-1;i>=0;i--){const fx=state.v09ImpactFx[i];fx.life-=.016;sceneCtx.save();sceneCtx.globalAlpha=Math.max(0,fx.life/.28);sceneCtx.fillStyle='rgba(255,255,255,.28)';sceneCtx.strokeStyle=fx.color;sceneCtx.lineWidth=5;sceneCtx.beginPath();sceneCtx.arc(q(fx.x),q(fx.y),fx.r,0,Math.PI*2);sceneCtx.fill();sceneCtx.stroke();sceneCtx.restore();if(fx.life<=0)state.v09ImpactFx.splice(i,1)}};
