// RAID QIX v1.2.1
(function ensureV121LoadoutDom(){
  const cg=document.getElementById('charmGrid');
  if(cg&&!cg.classList.contains('equipStrip')){
    cg.className='equipStrip';
    cg.innerHTML=`<button class="equipSlot" data-equip-slot="0"><span class="equipIndex">01</span><strong>EMPTY</strong><small>DROP / CLICK TO REMOVE</small></button><button class="equipSlot" data-equip-slot="1"><span class="equipIndex">02</span><strong>EMPTY</strong><small>DROP / CLICK TO REMOVE</small></button>`;
  }
  const oldGrid=document.getElementById('inventoryGrid');
  if(oldGrid&&!oldGrid.classList.contains('mcInventoryGrid')){
    const sec=oldGrid.closest('.section');
    if(sec){
      sec.classList.add('inventorySection');
      sec.innerHTML=`<h3>INVENTORY</h3><div class="inventoryWorkbench"><div class="inventoryPane"><div id="inventoryGrid" class="mcInventoryGrid"></div><div class="section muted" id="inventoryText"></div></div><div id="itemDetail" class="inventoryDetail"><strong>SELECT AN ITEM</strong><small>クリックで詳細。ドラッグで装備/合成。</small></div></div>`;
    }
  }
  if(!document.getElementById('v121RuntimeStyle')){
    const st=document.createElement('style');st.id='v121RuntimeStyle';
    st.textContent=`#loadoutScreen .panel{width:min(1180px,94vw);height:min(860px,92vh);overflow:hidden;display:flex;flex-direction:column}#loadoutScreen .section{margin-top:14px}.equipStrip{display:grid;grid-template-columns:1fr 1fr;gap:10px}.equipSlot{height:74px;border:1px solid #3a4653;background:#080d13;color:#fff;text-align:left;padding:10px 13px;position:relative;cursor:pointer}.equipSlot .equipIndex{position:absolute;right:8px;top:6px;font-size:9px;opacity:.38}.equipSlot strong{display:block;font-size:13px}.equipSlot small{display:block;margin-top:5px;font-size:9px;opacity:.58}.inventorySection{flex:1;min-height:0}.inventoryWorkbench{height:100%;display:grid;grid-template-columns:minmax(0,1fr) 310px;gap:14px;min-height:0}.inventoryPane{display:flex;flex-direction:column;min-height:0}.mcInventoryGrid{display:grid;grid-template-columns:repeat(9,minmax(0,1fr));gap:5px;overflow-y:auto;min-height:0;flex:1;padding:6px;background:#05080c;border:1px solid #27313c;align-content:start}.mcSlot{aspect-ratio:1/1;border:1px solid #303a46;background:#0b1118;color:#fff;position:relative;cursor:pointer;padding:4px;overflow:hidden}.mcSlot.empty{opacity:.22;cursor:default}.mcSlot.selected{outline:2px solid #fff}.mcSlot .slotFx{position:absolute;left:5px;top:4px;font-size:9px}.mcSlot .slotRank{position:absolute;right:4px;bottom:3px;font-size:9px}.mcSlot .slotGlyph{position:absolute;inset:18% 18% 20%;display:grid;place-items:center;font-size:22px}.inventoryDetail{border:1px solid #35414d;background:#0a1017;padding:18px;overflow:auto}.detailEquipGrid{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:16px}.detailUnequip{margin-top:7px;width:100%}`;
    document.head.appendChild(st);
  }
})();

const INVENTORY_VISIBLE_MIN=54;
function equippedSlotOf(uid){return state.equippedCharms.findIndex(x=>x===uid)}
function saveEquipped(){state.equippedCharms=state.equippedCharms.filter(uid=>proceduralCharmByUid(uid)).slice(0,2);save('raidqix.charms',state.equippedCharms);updateHud()}
function equipCharmToSlot(uid,slot){const charm=proceduralCharmByUid(uid);if(!charm||slot<0||slot>1)return false;state.equippedCharms=state.equippedCharms.filter(x=>x!==uid);while(state.equippedCharms.length<2)state.equippedCharms.push(null);state.equippedCharms[slot]=uid;state.equippedCharms=state.equippedCharms.filter(Boolean);saveEquipped();renderLoadoutV121();v121RenderDetail(charm);return true}
function unequipSlot(slot){if(slot<0||slot>1)return;const next=[state.equippedCharms[0]||null,state.equippedCharms[1]||null];next[slot]=null;state.equippedCharms=next.filter(Boolean);saveEquipped();renderLoadoutV121();v121RenderDetail(proceduralCharmByUid(state.selectedInventoryCharm)||null)}
function unequipCharmUid(uid){state.equippedCharms=state.equippedCharms.filter(x=>x!==uid);saveEquipped();renderLoadoutV121();v121RenderDetail(proceduralCharmByUid(state.selectedInventoryCharm)||null)}
function charmGlyph(c){if(!c?.affixes?.length)return '◇';const k=c.affixes[0].key;return ({SPD:'»',HP:'♥',CDR:'⌁',DRAW:'✦',CORE:'◆',SAVE:'⊕',DASH:'➤',LUCK:'✧',ARM:'⬡',ARC:'⌁'})[k]||'◇'}
function rarityClass(c){return `rarity-R${Math.max(1,Math.min(5,c?.rarity||1))}`}
function renderEquipSlots(){document.querySelectorAll('.equipSlot').forEach((el,slot)=>{const uid=state.equippedCharms[slot],c=proceduralCharmByUid(uid);el.className=`equipSlot${c?' filled '+rarityClass(c):''}`;if(c){el.innerHTML=`<span class="equipIndex">0${slot+1}</span><strong>${c.name}</strong><small>${charmAffixText(c)} · CLICK TO UNEQUIP</small>`;el.onclick=()=>unequipSlot(slot);el.draggable=true;el.ondragstart=e=>e.dataTransfer.setData('text/charm-uid',c.uid)}else{el.innerHTML=`<span class="equipIndex">0${slot+1}</span><strong>EMPTY SLOT</strong><small>DROP CHARM HERE</small>`;el.onclick=null;el.draggable=false}el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();const uid=e.dataTransfer.getData('text/charm-uid');if(uid)equipCharmToSlot(uid,slot)}})}
function v121RenderInventory(){const grid=document.getElementById('inventoryGrid');if(!grid)return;grid.innerHTML='';const sorted=[...state.inventory].sort((a,b)=>b.rarity-a.rarity||a.name.localeCompare(b.name));const slotCount=Math.max(INVENTORY_VISIBLE_MIN,Math.ceil(sorted.length/9)*9);for(let i=0;i<slotCount;i++){const c=sorted[i],el=document.createElement('button');if(!c){el.className='mcSlot empty';el.disabled=true;grid.appendChild(el);continue}const equipped=equippedSlotOf(c.uid);el.className=`mcSlot ${rarityClass(c)}${state.selectedInventoryCharm===c.uid?' selected':''}`;el.draggable=true;el.dataset.uid=c.uid;el.title=`${c.name}\n${CHARM_RARITY_LABEL[c.rarity]} · ${charmAffixText(c)}`;el.innerHTML=`<span class="slotFx">${c.affixes.length}FX</span><span class="slotGlyph">${charmGlyph(c)}</span><span class="slotRank">R${c.rarity}${equipped>=0?' · E'+(equipped+1):''}</span>`;el.onclick=()=>{state.selectedInventoryCharm=c.uid;v121RenderInventory();v121RenderDetail(c)};el.ondblclick=()=>{const current=equippedSlotOf(c.uid);if(current>=0)unequipCharmUid(c.uid);else equipCharmToSlot(c.uid,state.equippedCharms.length<2?state.equippedCharms.length:1)};el.ondragstart=e=>e.dataTransfer.setData('text/charm-uid',c.uid);grid.appendChild(el)}document.getElementById('inventoryText').textContent=`${state.inventory.length} CHARMS · ${slotCount} SLOTS`}
function v121RenderDetail(c){const el=document.getElementById('itemDetail');if(!el)return;if(!c){el.className='inventoryDetail';el.innerHTML='<strong>SELECT AN ITEM</strong><small>正方形スロットをクリックすると詳細を表示します。</small>';return}const equipped=equippedSlotOf(c.uid);el.className=`inventoryDetail ${rarityClass(c)}`;el.innerHTML=charmDetailHtml(c)+`<div class="muted" style="margin-top:12px">UID ${c.uid}<br>${equipped>=0?'EQUIPPED IN SLOT '+(equipped+1):'NOT EQUIPPED'}</div><div class="detailEquipGrid"><button id="equipTo1" class="btn"><strong>SLOT 1</strong><small>${state.equippedCharms[0]===c.uid?'EQUIPPED':'EQUIP'}</small></button><button id="equipTo2" class="btn"><strong>SLOT 2</strong><small>${state.equippedCharms[1]===c.uid?'EQUIPPED':'EQUIP'}</small></button></div>${equipped>=0?'<button id="unequipSelected" class="btn detailUnequip"><strong>UNEQUIP</strong><small>装備から外す</small></button>':''}`;document.getElementById('equipTo1').onclick=()=>equipCharmToSlot(c.uid,0);document.getElementById('equipTo2').onclick=()=>equipCharmToSlot(c.uid,1);document.getElementById('unequipSelected')?.addEventListener('click',()=>unequipCharmUid(c.uid))}
function renderSkillOnlyV121(){const sg=document.getElementById('skillGrid');if(!sg)return;sg.innerHTML='';for(const s of DATA.skills){const el=document.createElement('button');el.className='card'+(state.equippedSkill===s.id?' selected':'');el.innerHTML=`<strong>${s.name}</strong><small>${s.description}<br>CD ${s.cooldown}s</small>`;el.onclick=()=>{state.equippedSkill=s.id;save('raidqix.skill',s.id);renderLoadoutV121()};sg.appendChild(el)}}
function renderLoadoutV121(){renderSkillOnlyV121();renderEquipSlots();v121RenderInventory();v121RenderDetail(proceduralCharmByUid(state.selectedInventoryCharm)||null);renderFusionSlots();updateFusionStatus()}
renderLoadout=renderLoadoutV121;
const _v100FuseFive121=typeof fuseFive==='function'?fuseFive:null;if(_v100FuseFive121){fuseFive=function(){_v100FuseFive121();state.equippedCharms=state.equippedCharms.filter(uid=>proceduralCharmByUid(uid));saveEquipped();renderLoadoutV121()}}
charmDefs=function(){return state.equippedCharms.map(proceduralCharmByUid).filter(Boolean)};
renderLoadoutV121();
